### ISSUE TITLE
Preferences aren't fully adjusted to dark theme

### ISSUE THREAD

**Issue by mniewrzal** [eclipse/tm4e#101]
Grammar preferences have some white spaces in dark theme.
![screenshot from 2017-05-22 09-40-44](https://cloud.githubusercontent.com/assets/7313031/26297346/bedd5104-3ed2-11e7-8a32-ebfa2addc2d3.png)

**Comment by angelozerr** [comment]
@mniewrzal tell me if it's better now.

**Comment by mniewrzal** [comment]
Much better, thanks!
