### ISSUE TITLE
CSS file isn't colored in generic editor

### ISSUE THREAD

**Issue by mniewrzal** [eclipse/tm4e#102]
I'm not fully sure if its a bug or something with my configuration. When I'm opening css file in generic editor its not colored but it works ok with TextMate editor and in preferences preview. I have all tm4e plugins and LSP4E. HTML file is colored correctly. I debug it for a moment and grammar is applied to TMPresentationReconciler when generic editor is opened.
![screenshot from 2017-05-22 09-55-32](https://cloud.githubusercontent.com/assets/7313031/26297928/69d83504-3ed5-11e7-9d2a-d1a184dc4eba.png)

**Comment by mickaelistria** [comment]
How did you provide the css grammar? From Preferences, from BlueSky, from a
plugin of yours...?

**Comment by mniewrzal** [comment]
It's defined in org.eclipse.tm4e.samples plugin.

**Comment by angelozerr** [comment]
> It's defined in org.eclipse.tm4e.samples plugin.

I think the problem it's because of samples.

https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.samples/plugin.xml#L96 should be :

```
 <presentationReconciler
            class="org.eclipse.tm4e.ui.text.TMPresentationReconciler"
            contentType=org.eclipse.tm4e.samples.css">
      </presentationReconciler> 

```

and not:

```
 <presentationReconciler
            class="org.eclipse.tm4e.ui.text.TMPresentationReconciler"
            contentType="org.eclipse.languageserver.languages.css">
      </presentationReconciler> 

```

**Comment by mniewrzal** [comment]
Ah yes, I forgot to check this extension point. The same situation is with json and c#. I will send patch to fix it. Thanks for help!
