### ISSUE TITLE
Check  TextMate file extension "*.tmLanguage","*.json" when grammar must be selected

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#105]
Check TextMate file extension "*.tmLanguage","*.json" when grammar must be selected in the import wizard.

**Comment by angelozerr** [comment]
@moberhuber I have added a filter for TextMate file extension:

![image](https://cloud.githubusercontent.com/assets/1932211/26306317/38e9c408-3ef3-11e7-8348-1dd65611ce8b.png)

Tell me if you need more thing

**Comment by moberhuber** [comment]
Looks nice - thanks!

My comment was originally meant more as a question (I don't even know if 
*.tmLanguage is a standard extension). Didn't expect this to be added so 
quickly -- but it looks like a nice improvement :)

Cheers,
Martin

**Comment by angelozerr** [comment]
> Looks nice - thanks!

Thanks!

> (I don't even know if *.tmLanguage is a standard extension

Yes it's a standard extension for TextMate.
