### ISSUE TITLE
OnigString.uniqueId seems of no use

### ISSUE THREAD

**Issue by fabioz** [eclipse/tm4e#108]
Right now, OnigString.uniqueId seems to be used as a caching in org.eclipse.tm4e.core.internal.oniguruma.OnigRegExp.Search(OnigString, int), yet, the IGrammar.tokenizeLineXXX methods all receive a String (which always creates a new OnigString), so, that caching never actually works with this API... (or am I misreading something?)

It's also interesting that the grammar seems to come from vscode from the comments (https://github.com/Microsoft/vscode-textmate/blob/master/src/main.ts), yet, that caching seems to come from atom (https://github.com/atom/node-oniguruma/blob/master/src/onig-string.cc / and https://github.com/atom/node-oniguruma/blob/master/src/onig-reg-exp.cc), so, maybe something got lost when putting things together?

If it's really unused, an enhancement could be just don't compute that cache and don't compute the uniqueId (that way the time to calculate the UUID using UUID.randomUUID can be eliminated) -- although if the cache does make sense, a different API should probably be available.

**Comment by fabioz** [comment]
Actually closing... I think I misunderstood things (the cache seems to be there because a given regexp may be searched multiple times for the same line, although I still need to check a bit more).

UUID could still be removed just for uniqueId = new Object(), as it's being compared by identity.

**Comment by angelozerr** [comment]
@fabioz I have done the same thing than https://github.com/atom/node-oniguruma/blob/master/src/onig-reg-exp.cc#L31

This code was intruduced inside node-oniguruma with the PR https://github.com/atom/node-oniguruma/commit/f60ec4bb1f663c473824850dd267c550523720bf 

To be honnest with you, I have not try to understand more this logic, but this cache improve a lot performances.

> UUID could still be removed just for uniqueId = new Object(), as it's being compared by identity.

Do you think it's better for performance? Could you create a PR please. Thanks!
