### ISSUE TITLE
Duplicate source entry on https://projects.eclipse.org/projects/technology.tm4e/developer

### ISSUE THREAD

**Issue by vogella** [eclipse/tm4e#109]
I think both entries point to the same location.

![image](https://user-images.githubusercontent.com/139910/27031403-6b4f39f4-4f70-11e7-85da-d43a3dfffd28.png)

**Comment by angelozerr** [comment]
@vogella I don't know why it does that. I have just filled one line and it appears 2 lines?

**Comment by vogella** [comment]
Maybe ask webmaster@eclipse.org?

Am 12.06.2017 6:02 nachm. schrieb "Angelo" <notifications@github.com>:

**Comment by eclipsewebmaster** [comment]
I removed and re-added your source repo and Github repo and now there is only the one entry on the developer tab.  If you see this again I suggest you file a bug against community -> pmi

**Comment by angelozerr** [comment]
Thanks @eclipsewebmaster !
