### ISSUE TITLE
Theme association for a given grammar

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#117]
Today `Dark` Textmate theme is used when  `Dark`  Eclipse E4 theme is selected and `Solarized Light`  Textmate theme otherwise.

It should be cool if user could select the prefered TextMate theme for each Eclipse E4 theme. I have started to implement that, now UI preferences must be finsished by implementing the New button:

![](https://user-images.githubusercontent.com/1932211/27130731-cd68ece6-5107-11e7-9c66-99e8d424c18a.png)

**Comment by angelozerr** [comment]
@mickaelistria do you think it's a problem if we add a new dependenciy to the `org.eclipse.ui.themes` to retrieve name of the E4 theme an dlist of E4 Theme id?

**Comment by mickaelistria** [comment]
I don't see any issue with adding a dependency to this bundle. I think this bundle is even required for the IDE to work properly, so adding a depedency to it shouldn't have any bad effect on the compatibility.

**Comment by angelozerr** [comment]
@mickaelcaistria I post this question because I tell me more and more if tm4e could be used outside the IDE like JFace Text.

**Comment by mickaelistria** [comment]
It's up to you, but I don't imagine many users of TM4E outside of the Eclipse IDE story.

**Comment by angelozerr** [comment]
Ok thanks for your answer. I would like to know your opinion. If one day some user wish to use tm4e outside IDE, we will see. Thanks @mickaelistria !

**Comment by angelozerr** [comment]
@eliasvasylenko @mickaelistria now you can select a theme for a given grammar with preferences. Here a demo:

![themepreferencesdemo](https://user-images.githubusercontent.com/1932211/27506806-7a6a2bb0-58c1-11e7-9b15-75d778b5aafc.gif)

Any feedback are welcome!

Thanks!
