### ISSUE TITLE
Provide contextual menu to select theme for an editor bound with TMPresentationReconciler

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#118]
Today the only way to bind grammar with them eis to do with preferences:

![](https://user-images.githubusercontent.com/1932211/27506806-7a6a2bb0-58c1-11e7-9b15-75d778b5aafc.gif)

It should be cool if we could have a contextual menu like this

 * TextMate 
   * Themes
    * Light
    * Soloraized Light

available when editor is bound with TMPresentationReconciler.

@mickaelistria what do you think?

**Comment by mickaelistria** [comment]
In general, context-menus in Eclipse IDE are an example of why Eclipse IDE feels heavy. Adding context-menu should be done only if considered as very useful for most users. In such case, I'm not convinced it is. Showing the Preference page when users hits "Preferences" context-menu for an editor and initiate this preference page according to the current grammar/theme would probably be a good enough UX.

**Comment by angelozerr** [comment]
@mickaelistria I have not seen your answer -( I have soon finished my work. Here a demo:

![themechangecontextualmenu](https://user-images.githubusercontent.com/1932211/27586756-f10e4d32-5b41-11e7-8caf-4ba864309912.gif)

If you don't like, I will not commit my work.

**Comment by mickaelistria** [comment]
It's all up-to-you. As long as it doesn't come by default in the Generic Editor, I'm fine with it.
Note that end-users wouldn't get the purpose of the menu. "TextMate" isn't the concept there, the concept is the Theme. You'd rather rename "TextMate..." menu into "Theme" and move it closer from Preferences as it doesn't actually perform a coding action like other menus of this group.

**Comment by angelozerr** [comment]
> As long as it doesn't come by default in the Generic Editor

This menu is displayed only if the editor uses TMPresentationReconclier.

> Note that end-users wouldn't get the purpose of the menu. "TextMate" isn't the concept there, the concept is the Theme. 

Yes sure, but my idea was to have a generic TextMate menu and have that:

* TextMate
  * Theme 
    * Light
    * Solaried Light
  * Open grammar (open the grammar in a TextMate editor grammar)
  * Other menus?

**Comment by mickaelistria** [comment]
What are the user-stories behind "Open grammar" menu? Which ratio of users would use it?

**Comment by angelozerr** [comment]
This "Open grammar" menu" should come from to a new textmate tooling plugin (which hosts the TextMate grammar editor). So so the idea if you will not install the future TextMate toolings, you will have not this menu.

I tell me to provide a TextMate menu and set other contextual menu used for TextMate

**Comment by mickaelistria** [comment]
End-users actually don't care about TextMate being used as a backend for
coloration. They just like to see things working
To be honest, I'm not found of such a TextMate context-menu. I think it's
not well integrated into typical IDE UX (where people control themes via
preferences) and changing themes via context-menu isn't very useful on a
day-to-day work. The Context-Menu on an editor has to be as productive as
possible and contain only things that are usually useful to the majority of
users, changing TextMate themes isn't part of such operations IMHO.
About opening the Grammar from context-menu, it's even worse: I suspect way
less than 1% of users would actually like to do it!

In my opinion, all those pure TextMate features should be accessible from a
single and same entry point, and the Preference Page is great for that.

**Comment by angelozerr** [comment]
Many thanks @mickaelistria to take time to answer me.

I understand now that contextual menu for editor must contains the items menu that user uses a lot.

My main motivation to provide this TextMate contextual menu is to simplify the theme changed. Tody you need to open preferences, go at grammar preference page, select the well grammar, select the theme tab and click on "New" button to open a wizard and select the theme. I find it's very boring.

I think I will commit my work because there are some interesting features like PropertyTester#canSupportTextMate to know if a given editor part can support TextMate (if the editor is linked to TMPresentationReconciler). I commit my work and if you (and other users) wish that I remove contextual menu, I will do it.

**Comment by angelozerr** [comment]
@mickaelistria I have finished this issue, please tell me what you think (for code if you have time):

![image](https://user-images.githubusercontent.com/1932211/28786629-0e4c7944-761a-11e7-823f-45c165113a4f.png)

**Comment by mickaelistria** [comment]
As mentioned earlier, I do not think this feature is worth being shown in
context menu. Keeping context menu focused on productivity and minimizing
the "noise" and focusing on recurring or very narrowly scope operations is
that's best. I'd rather imagine the way to select a theme for the editor as
a page in the editor's "Properties" dialog.

**Comment by angelozerr** [comment]
Thanks again @mickaelistria for your feedback. I will try to find time to study your idea.

**Comment by mickaelistria** [comment]
This was implemented some time ago.
