### ISSUE TITLE
Bracket and brace matching and autotype

### ISSUE THREAD

**Issue by am2605** [eclipse/tm4e#119]
Maybe I'm getting a bit ahead of myself, but is it possible for the tm4e editor to highlight matching brackets and braces, and also autoclose them when you type?

**Comment by mickaelistria** [comment]
Do TM Grammars define the possible brackets or open/close tokens? The goal of this question is to identify whether TM is the right layer for it or not.
Ideally, I don't think it'd be only a matter of brackets, but any insertion of text should automatically trigger the insertion of the minimal sample of code to keep the text as valid as possible according to grammar. So if one enter a `for` in Java, with the TM Grammars, it could be possible to automatically insert the `( ; ; )` afterwards as there is probably a grammar rule for that.

**Comment by am2605** [comment]
That's an excellent question and unfortunately I don't know enough about TM grammars to be able to answer you.
This is the one I am using if you are able to take a look, but I understand if you do not have the time to do so 
https://github.com/ilich/vscode-coldfusion/blob/master/syntaxes/cfml.tmLanguage
		

		
	





On Mon, Jul 3, 2017 at 5:45 PM +1000, "Mickael Istria" <notifications@github.com> wrote:












Do TM Grammars define the possible brackets or open/close tokens? The goal of this question is to identify whether TM is the right layer for it or not.

Ideally, I don't think it'd be only a matter of brackets, but any insertion of text should automatically trigger the insertion of the minimal sample of code to keep the text as valid as possible according to grammar. So if one enter a for in Java, with the TM Grammars, it could be possible to automatically insert the ( ; ; ) afterwards as there is probably a grammar rule for that.

**Comment by angelozerr** [comment]
I remember that VSCode provide matchBracket https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/textModelWithTokens.ts#L481 but never studied it.

I think we could provide a new method `ITModel#matchBracket (Position position)` to support matching bracket. For the other feature like close bracket, I'm not sure that VSCode does that.

**Comment by svenefftinge** [comment]
vscode does it declaratively through json: 
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages

**Comment by angelozerr** [comment]
Indeed @svenefftinge I have noticed that and I tell me more and more that Generic Editor should support this kinf of JSON Language Client configuration. Like textmate grammar we could use this JSON configuration from VSCode languages.

**Comment by mickaelistria** [comment]
This won't be added to Generic Editor directly, but it would be possible to implement an IAutoEditStrategy for such file; and as @angelozerr mentioned, very similarly to how tm4e provides extension for IPresentationReconciler and grammars.

**Comment by angelozerr** [comment]
@mickaelistria @svenefftinge I have started to develop auto close feature by using VSCode language configuration.

Here a sample typescript language configuration

```
"autoClosingPairs": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"],
        { "open": "'", "close": "'", "notIn": ["string", "comment"] },
        { "open": "/**", "close": " */", "notIn": ["string"] }
    ],
```

that I use in the following demo :

![autoclosedemo](https://user-images.githubusercontent.com/1932211/29377557-70c2c822-82bc-11e7-9b2b-dffb611ce1cc.gif)

As you can see,the `notIn` is not implemented because we need token information. VSCode uses the textmate model to know the token information.

The question is where we could host this project:

 * @mickaelistria if you are OK, I will push my work. I have created a new plugin org.eclipse.tm4e.languages which support for the moment autoClosingPairs. 
 * host in the generic editor. We could use autoClosingPairs without notIn and GenericEditor could provide an extension point for know the token information. tm4e could implement this extension point.

@mickaelistria I'm waiting for your decision, Thanks!

**Comment by mickaelistria** [comment]
I don't think Platform Text is the right place to host some parsers for file formats specific to VSCode. We actually want to prevent Eclipse Platform from strongly relying or doing the maintenance of some external technologies which are not fully standardized or for which future in uncertain.

These autoClosingPairs from such description file could be contributed as an autoEditStrategy to the generic editor using the regular extension point https://www.eclipse.org/eclipse/news/4.8/M1/#generic-editor-autoeditstrategies . At the moment, I have the impression tm4e is the best candidate to host that. So it seems all good as it is now.

**Comment by angelozerr** [comment]
> These autoClosingPairs from such description file could be contributed as an autoEditStrategy to the generic editor using the regular extension point https://www.eclipse.org/eclipse/news/4.8/M1/#generic-editor-autoeditstrategies 

I have exactly done that.

> At the moment, I have the impression tm4e is the best candidate to host that. So it seems all good as it is now.

Very cool! I have created an issue at https://github.com/eclipse/tm4e/issues/132

**Comment by angelozerr** [comment]
I close this issue because I'm implementing that with VSCode language configuration.

You can see demo of my current work at https://github.com/eclipse/tm4e/issues/132#issuecomment-324869181
