### ISSUE TITLE
Move to Eclipse.org

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#12]
As this project fits in the big theme of Eclipse Platform and IDE "[Reduce cost of adding support for new languages](https://wiki.eclipse.org/Platform_UI/Plan/4.7#Reducing_cost_of_basic_support_for_new_languages)" and as it completes the [LSP4E](https://projects.eclipse.org/proposals/lsp4e/) project which is missing a good implementation of syntax highlighting, this Eclipse/TextMate integration would be a great project to contribute to Eclipse.org!

Current state:
- [x] Project approved and provisioned https://projects.eclipse.org/projects/technology.tm4e
- [x] Move to version 0.1.0 (issue #35)
- [x] Get confirmation for copyright header and update if necessary, see #37 and #39 
- [x] Create CQ for initial contribution https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12577

Blockers
- [ ] Create CQ for jcodings use in TM4E (piggy back Orbit CQ)
- [ ] Create CQ for joni use in TM4E (piggy back Orbit CQ)
- [ ] GitHub repository at Eclipse.org
- [ ] Push initial code to Eclipse GitHub repo

Other tasks (releng) are non-blockers and will be tracked in the "official" repo

**Comment by mickaelistria** [comment]
FYI @angelozerr and I are working on a [project proposal ](https://www.eclipse.org/projects/tools/proposals.php) at Eclipse.org . Please comment if you're interested.

**Comment by angelozerr** [comment]
@mickaelistria I will change package to **org.eclipse.textmate4e**, but I have a question. Today we have 2 plugins:

 * core : **org.eclipse.language.textmate.core** will become **org.eclipse.textmate4e.core**. This plugin provides the TextMate tokenizer which works with String line (like vscode-textmate). It doesn't depend on Eclipse. It could be used with Swing too. See https://github.com/angelozerr/textmate.java/wiki/Core
 * eclipse: **org.eclipse.language.textmate.eclipse** will become **org.eclipse.textmate4e.eclipse**. This plugin bind Eclipse Document with  the engine of TextMate coming from the core.

I find name **org.eclipse.textmate4e.eclipse** is strange (it has 2 eclipse in the name).

What is your suggestion about that?

 * merge core+eclipse plugins in one?
 * or find an another name for **org.eclipse.textmate4e.eclipse**

Thank's for your suggestion!

**Comment by mickaelistria** [comment]
what about using `org.eclipse.textmate4e.ui` or `org.eclipse.textmate4e.ide` ?

**Comment by angelozerr** [comment]
Thanks @mickaelistria for your suggestion. See https://github.com/angelozerr/textmate.java/issues/16

**Comment by paulvi** [comment]
Note, this somehow competes with https://github.com/fabioz/LiClipseText by @fabioz

Is there waste of effort happening? Or Fabio was not eager enough to contribute to Eclipse ?

**Comment by angelozerr** [comment]
> Note, this somehow competes with https://github.com/fabioz/LiClipseText by @fabioz

At first, my main goal was to support advanced syntax coloration (like VSCode) for TypeScript https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.2.0#textmate

 I have tried LiClipseText project. It works great but here the reaso why I have decided to create TM4E:

 * LiClipseText requires to use the LiClipseText  editor. In typescript.java I don't want to use LiClipseText  as editor base. In my case I would like to have just a TextMatePresentationReconcilier which could work with any editor.  See https://github.com/angelozerr/textmate.java/blob/master/org.eclipse.tm4e.samples/src/main/java/org/eclipse/tm4e/samples/php/PHPViewerConfiguration.java
 * LiClipseText  seems not to support standard TextMate grammar (when I have tried to use VSCode TypeScript gramar I had some problems).
 * with big file like https://raw.githubusercontent.com/Microsoft/TypeScript/master/lib/tsserver.js the editor frozen while a long time. I have tried to avoid that by colorizing some part of the editor (like VSCode does), there is some bugs, but it starts working.

TM4E is a port of vscode-textmate and almost test of vscode-textmate passed with TM4E, so I'm almost sure that I have the same renderer than VSCode by using TextMate grammar from VSCode, Atom, etc 

> Is there waste of effort happening? 

Perhaps, but I think TM4E is easy to integrate with any editors. For the moment it supports only syntax coloration, perhaps it could support other features than folding, etc

> Or Fabio was not eager enough to contribute to Eclipse ?

I don't know about  that.

**Comment by mickaelistria** [comment]
> Is there waste of effort happening?

I agree with Angelo that at the moment, tm4e is a more focused on textmate grammar support and easier to reuse component in Eclipse IDE without requiring specific editors and so on. It's a simpler piece of code to migrate and use at Eclipse.org than Liclipse is.

> Or Fabio was not eager enough to contribute to Eclipse ?

Indeed. I also tried to contribute some extensions to Liclipse about having it more easily usable in existing editors and generic editor, but it has been ignored.
So let's say that the entire enthusiasm from Angelo and the lack of stated motivation from Liclipse make that although being technically related, there is no doubt about which one is better at Eclipse.org.

**Comment by fabioz** [comment]
Hi there, as a note, yes, I wasn't very eager to put LiClipseText into Eclipse (I like it better in the marketplace than embedded into the Eclipse codebase and I think that although there's one common target: textmate support, the final targets of LiClipse actually aim higher).

Regarding the support, it's also correct, I think right now LiClipseText doesn't grok all of textmate (although it has a reasonable support, I did it from scratch only from looking at the textmate grammar) -- maybe I'll follow along: getting a pre-made version from vscode was a pretty good idea, so, maybe in the future I'll just end up reusing this code too ;)

Regarding the pull request, I'm sorry about that... somehow GitHub didn't notify me properly -- but now that I saw your comment here, I answered you there ;)

**Comment by angelozerr** [comment]
> maybe I'll follow along: getting a pre-made version from vscode was a pretty good idea, 

Thanks @fabioz ! Glad you like this idea.

> so, maybe in the future I'll just end up reusing this code too ;)

It should be fantastic to benefit with your great capability. My integration of TextMate is not perfect with big files, so any contribution are welcome!

**Comment by fabioz** [comment]
> It should be fantastic to benefit with your great capability. My integration of TextMate is not perfect with big files, so any contribution are welcome!

:)

**Comment by mickaelistria** [comment]
I think we're done there. All the necessary legal stuff are done and code actually moved to a GitHub repo under the @eclipse foundation.

**Comment by mickaelistria** [comment]
Thanks @angelozerr for this huge contribution to @eclipse !

**Comment by angelozerr** [comment]
You are welcome @mickaelistria! Thanks to you to help me to move tm4e to Eclipse.org

Next step, find strong contributors to stabilize tm4e and fix bugs with model synch with editor.

**Comment by paulvi** [comment]
- [ ] README should be updated to show the status, point to new repo

**Comment by angelozerr** [comment]
> README should be updated to show the status, point to new repo

Yes sure, I'm waiting for the work of @mickaelistria with jobs and update site to change that.
