### ISSUE TITLE
How to install TM4E in Eclipse Oxygen?

### ISSUE THREAD

**Issue by ainslec** [eclipse/tm4e#121]
How do I install TM4E in Oxygen. what is method for installing the plugin?

After upgrading from Mars to Oxygen it appears my plugin is failing with the following error.

![image](https://user-images.githubusercontent.com/201870/28583484-3aeb198c-7161-11e7-8cf2-630732a88364.png)

**Comment by angelozerr** [comment]
I think your code is out of dated. The `org.eclipse.tm4e` exported package doesn't exists.  I think you will have the same problem with Mars. To install it, you can do it with update site http://download.eclipse.org/tm4e/snapshots/

**Comment by ainslec** [comment]
I'm still having problems with launching TM4E on Oxygen.

Here are my plugin settings for my Eclipse Run Configuration profile :

![image](https://user-images.githubusercontent.com/201870/28585987-1f449cae-716a-11e7-922c-e025f04250ab.png)

![image](https://user-images.githubusercontent.com/201870/28585948-f23b91cc-7169-11e7-9e08-5c90b8cb5f95.png)

When I launch the Eclipse I get the following message:

![image](https://user-images.githubusercontent.com/201870/28586029-463bee16-716a-11e7-80da-d27a5771e1f8.png)

Then when I start it, I receive the following exception, after which nothing is syntax highlighted:

Starting my plugin gives me the following exception:

>   Unresolved requirement: Require-Bundle: org.eclipse.tm4e.ui
>     -> Bundle-SymbolicName: org.eclipse.tm4e.ui; bundle-version="0.1.0.201706241504"; singleton:="true"
>        org.eclipse.tm4e.ui [1075]
>          Unresolved requirement: Require-Bundle: org.eclipse.tm4e.core
>            -> Bundle-SymbolicName: org.eclipse.tm4e.core; bundle-version="0.1.0.201706121412"
>               org.eclipse.tm4e.core [1073]
>                 Unresolved requirement: Require-Bundle: org.joni; bundle-version="2.1.11"
>                   -> Bundle-SymbolicName: org.joni; bundle-version="2.1.11.v20170306-1742"
>                      org.joni [1080]
>                        Unresolved requirement: Import-Package: org.objectweb.asm; version="5.0.3"
>          Unresolved requirement: Require-Bundle: org.eclipse.tm4e.registry
>            -> Bundle-SymbolicName: org.eclipse.tm4e.registry; bundle-version="0.1.0.201706232023"; singleton:="true"
>               org.eclipse.tm4e.registry [1074]
>                 Unresolved requirement: Require-Bundle: org.eclipse.tm4e.core
>                   -> Bundle-SymbolicName: org.eclipse.tm4e.core; bundle-version="0.1.0.201706121412"
>   Unresolved requirement: Require-Bundle: org.eclipse.tm4e.ui.editor
>     -> Bundle-SymbolicName: org.eclipse.tm4e.ui.editor; bundle-version="0.1.0.201705041058"; singleton:="true"
>        org.eclipse.tm4e.ui.editor [1076]
>          Unresolved requirement: Require-Bundle: org.eclipse.tm4e.ui
>            -> Bundle-SymbolicName: org.eclipse.tm4e.ui; bundle-version="0.1.0.201706241504"; singleton:="true"
>          Unresolved requirement: Require-Bundle: org.eclipse.tm4e.registry
>            -> Bundle-SymbolicName: org.eclipse.tm4e.registry; bundle-version="0.1.0.201706232023"; singleton:="true"
>          Unresolved requirement: Require-Bundle: org.eclipse.tm4e.core
>            -> Bundle-SymbolicName: org.eclipse.tm4e.core; bundle-version="0.1.0.201706121412"
>   Unresolved requirement: Require-Bundle: org.eclipse.tm4e.ui.editor
>     -> Bundle-SymbolicName: org.eclipse.tm4e.ui.editor; bundle-version="0.1.0.201705041058"; singleton:="true"
>   Unresolved requirement: Require-Bundle: org.eclipse.tm4e.registry
>     -> Bundle-SymbolicName: org.eclipse.tm4e.registry; bundle-version="0.1.0.201706232023"; singleton:="true"

**Comment by mickaelistria** [comment]
> Unresolved requirement: Import-Package: org.objectweb.asm; version="5.0.3"

Make sure you have asm 5.0.3 or newer in your target-platform.

**Comment by angelozerr** [comment]
@ainslec can we close this issue?

**Comment by ainslec** [comment]
I still can't get past this issue.

![image](https://user-images.githubusercontent.com/201870/28758181-c01393fe-758b-11e7-9e31-c6eb136c28a1.png)

I have 5.0.1 and 5.2.0 asm plugins on my system and I still get the following error messages (and a load of OSGi linking problems) when trying to run an Eclipse workspace. Now, I don't know how to get 5.0.3, I would have assumed if it was required for TM4E that it would have been installed via the "Add New Software" wizard. If I have to explicitly install 5.0.3, please can you point me how and where to get the Eclipse plugin because usually when I install plugins they automatically install their pre-requisites and I would not know where to look for asm/eclipse in isolation as it is a library rather than a plugin of its own.

It may be that I'm not running the recent version. The update site seems to be : http://download.eclipse.org/tm4e/snapshots/

Here is the required bundle list for my MANIFEST.MF associated with my plugin:

Require-Bundle: org.eclipse.ui,
 org.eclipse.core.runtime,
 org.eclipse.core.resources,
 org.eclipse.jdt.launching,
 org.eclipse.jdt.core,
 org.eclipse.debug.ui,
 org.eclipse.jdt.debug,
 org.eclipse.jdt.debug.ui,
 org.eclipse.jdt.ui,
 org.eclipse.jface.text,
 org.eclipse.ui,
 org.eclipse.core.resources,
 org.eclipse.core.filesystem,
 org.eclipse.ui.editors,
 org.eclipse.ui.views,
 org.eclipse.tm4e.core;bundle-version="0.1.0",
 org.eclipse.tm4e.ui,
 org.eclipse.tm4e.ui.editor,
 org.eclipse.tm4e.registry,
 org.eclipse.tm4e.ui.editor

Here is how I'm referencing tm4e from my plugin.xml:

![image](https://user-images.githubusercontent.com/201870/28758257-a0d76924-758c-11e7-93ef-a39eb6888817.png)

You mentioned that I should not use a tm4e editor and rather use a generic editor. I am confused as to the distinction. When I was running this plugin in the last year, I was running in the textmate editor panel and all was fine. Is all my code out of date now, should "org.eclipse.tm4e.ui", "org.eclipse.tm4e.ui.editor", etc, be something else?

Sorry for this, but just want to get my plugin working again. It can only be a config problem and I guarantee everything was working before Eclipse decided to update to Oxygen.

**Comment by angelozerr** [comment]
> I have 5.0.1 and 5.2.0 asm plugins on my system and I still get the following error messages (and a load of OSGi linking problems) when trying to run an Eclipse workspace.

If you check 5.2.0, is it working?

> You mentioned that I should not use a tm4e editor and rather use a generic editor.

The thing you muts understand is that if an editor which to consume TextMate, it must uses TMPresentationReconciler. There are 3 means to do that:

 1) Implement your own editor which consumes TMPresentationReconciler (I think it's your case)
 2) with TextMate Editor which is a TextEditor which consumes TMPresentationReconciler. So this editor works with any Eclipse version. See demo at https://twitter.com/angelozerr/status/860390898483548161
3) with Generic Editor, but as I said you, it's not implemented. See https://github.com/eclipse/tm4e/issues/17

**Comment by angelozerr** [comment]
@ainslec can we close this issue?

**Comment by ainslec** [comment]
Yes. Please close this issue.
