### ISSUE TITLE
Cannot access org.eclipse.tm4e.core.grammar.IGrammar in Oxygen, was working in Mars

### ISSUE THREAD

**Issue by ainslec** [eclipse/tm4e#122]
This code no longer seems to work in the new (Oxygen) version of the library. Has IGrammer been hidden?

![image](https://user-images.githubusercontent.com/201870/28587778-3d763c72-7170-11e7-9d77-8ec7d9de1043.png)

**Comment by angelozerr** [comment]
Like https://github.com/eclipse/tm4e/issues/121#issuecomment-317801415 your code is out of dated. IGrammar belongs to now https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.core/src/main/java/org/eclipse/tm4e/core/grammar/IGrammar.java

**Comment by ainslec** [comment]
Your linked class is the same class I am trying to access .. "org.eclipse.tm4e.core.grammar.IGrammar", but seems not accessible. Maybe not exported in the bundle via OSGi?

**Comment by angelozerr** [comment]
Please note that IGrammar is exported https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.core/META-INF/MANIFEST.MF#L17

**Comment by angelozerr** [comment]
@ainslec can we close this issue?

**Comment by ainslec** [comment]
Yes, I think so. I haven't resolved it on my end yet, but I'll re-open it to be more specific if it continues to be a problem.

**Comment by ainslec** [comment]
Even though this is closed already, just want to add a note that this is fully resolved at my end now.
