### ISSUE TITLE
Monokai theme colours different in text window versus preview.

### ISSUE THREAD

**Issue by ainslec** [eclipse/tm4e#124]
(Assume this is all via preference menu associations - no plugin code here)

In preview :

![monokai_wrong_2](https://user-images.githubusercontent.com/201870/28624204-4f25c726-7210-11e7-9d66-066f4080b7f7.png)

Rendered in TM4EEditor (the main text colour is much darker than in preview):

![monokai_wrong_1](https://user-images.githubusercontent.com/201870/28624187-3c5a75f6-7210-11e7-9faf-77712ac2d6c2.png)

My Eclipse theme is "dark" so I wonder if the default text colour is being inherited from the Eclipse theme rather than from the Textmate theme? (Also the background colour is wrong versus the preview)

**Comment by ainslec** [comment]
More information:

Confirmed I can change the default text colour here "foreground color" (but I don't think this should influence a carefully balanced theme - such as monokai):

![image](https://user-images.githubusercontent.com/201870/28624807-312c26b4-7212-11e7-8fc8-865c36f75b4b.png)

**Comment by angelozerr** [comment]
Today preview StyledText uses hard coded black color. Indeed it should be better to use black color from preferences. Any PR are welcome!

**Comment by ainslec** [comment]
My point isn't that the preview window is using an incorrect background colour (it is). It is that the textmate editor background colour is using the wrong colour too. It is using the text editor colour from preferences, when it should be using the background colour from the textmate style.

When I create a textmate style, or use a textmate style, it is really important that the background colour I wish to use is rendered, or if not, at least I can manually modify it in Eclipse without changing the background colour of unassociated editors (via the text editor dialog).

**Comment by angelozerr** [comment]
Same issue than https://github.com/eclipse/tm4e/issues/115
