### ISSUE TITLE
Can't associate contentType and grammar correctly

### ISSUE THREAD

**Issue by jabby** [eclipse/tm4e#128]
Hello, 

I tried to create association in an eclipse plugin between a contentType and a grammar but I don't understand why the association is not good. 
I tried to add less and scss syntax highlighting. 

The code sample is here : https://github.com/jabby/eclipse-bluesky

Can someone explain where is my mistake ?

**Comment by angelozerr** [comment]
Do you see your regisetred grammar in the Window / TextMate / Grammar preferences?

**Comment by jabby** [comment]
Ok I understand the problem I had. The grammar was present in Window / TextMate / Grammar preferences but I was not allowed to load the gramar. In fact, in the less.tmLanguage.json the scopeName is source.css.less. In plugin.xml I made  mistake and used source.less instead.

I fix 2 typos (less and scss) and now the grammar is correctly loaded. 

By the way do you now where I can find some documentation on tm4e / textmate ? I would like to change the color of the highlighting.

**Comment by angelozerr** [comment]
> By the way do you now where I can find some documentation on tm4e / textmate ?

https://github.com/eclipse/tm4e/wiki/UI any contribution are welcome if it misses something.

>  I would like to change the color of the highlighting.

You mean occurrences? 

Please note that I have improved yesterday the capability to customize backgound/foreground of StyledText with Textmate theme and "current line hihglight".

**Comment by jabby** [comment]
Thanks for your answer I will check this next week. 

```` 
You mean occurrences?
````

I don't understand.

**Comment by angelozerr** [comment]
> I don't understand.

I mean coloration when editor marks occurences for instance. What do you mean with 

> I would like to change the color of the highlighting.
