### ISSUE TITLE
Use an Eclipse-like theme by default

### ISSUE THREAD

**Issue by svenefftinge** [eclipse/tm4e#131]
It would be nice if the default theme would be aligned with the standard Eclipse syntax coloring.

**Comment by angelozerr** [comment]
I'm not a big fan of standard Eclipse syntax coloring. 

I prefer this look:

![image](https://user-images.githubusercontent.com/1932211/29131403-0d7f8f50-7d2d-11e7-9a22-dfe08f556191.png)

than:

![image](https://user-images.githubusercontent.com/1932211/29131453-3a791774-7d2d-11e7-9e9b-533813797c36.png)

To provide standard Eclipse syntax coloring, I think we must wait for https://github.com/eclipse/tm4e/issues/2 to provide a TextMate theme and not a CSS file.

**Comment by boniatillo-com** [comment]
Hi,

I'm not a big fan of standard Eclipse syntax coloring neither but I am used to it, I think to keep a consistent style by default is good.

At least to keep the keywords, string and number colors.

**Comment by mickaelistria** [comment]
I started an "Eclipse Light" theme that end-users could use if they feel nostalgic of default JDT style. It's very dummy and incomplete (so it TextMate in general), but still shows usual colors for keywords, comments and strings. PR welcome at https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui/themes/Eclipse-light.css

I'm also in agreement with @angelozerr that this shouldn't necessarily become the default. Sure, the default theme is different from usual and users are disturbed by this difference, but I think it's worth it in term of comfort. Moreover, it highlights users that the theme is not set in stone and suggests it can be configured.

**Comment by mickaelistria** [comment]
I'm closing this one. The Eclipse theme is shipped by default, but not enabled by default.
TM4E brings richer color palette by default, it's nice that users can see it.
