### ISSUE TITLE
Support for language-configuration.json (VSCode)

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#132]

**Comment by angelozerr** [comment]
@mickaelistria where can I host my work with language configuration ?

 * create a new project org.eclipse.tm4e.languageconfiguration?
 * or use existing  org.eclipse.tm4e.ui and I use org.eclipse.tm4e.ui.languageconfiguration package name?

**Comment by angelozerr** [comment]
@mickaelistria after thinking, I would like to create a new plugin `org.eclipse.tm4e.languageconfiguration`. I will start with that, if you prefer other things, don't hesitate to tell me, thanks!

**Comment by mickaelistria** [comment]
I agree a new plugin is better.

**Comment by angelozerr** [comment]
@mickaelistria  I have started to implement `auto close` and `on enter` support

 * here a little demo with JSON which doesn't use language configuration

![jsonwithoutlanguageconfiguration](https://user-images.githubusercontent.com/1932211/29708098-dcd0f382-8987-11e7-8acd-60867502cde0.gif)

 * here a little demo with JSON with  language configuration:

![jsonwithlanguageconfiguration](https://user-images.githubusercontent.com/1932211/29708105-e0706d74-8987-11e7-848f-7c8b744563c5.gif)

My next work is to implement surrounf of characters pairs, but if we wish to use it with generic editor, it must support extension point to define `characterPairMatcher `https://bugs.eclipse.org/bugs/show_bug.cgi?id=521031

**Comment by angelozerr** [comment]
@ mniewrzal I think you could integrate language configuration in https://github.com/eclipselabs/language-servers-for-eclipse like I have done for blue sky https://github.com/mickaelistria/eclipse-bluesky/pull/34

**Comment by mickaelistria** [comment]
What's missing here? Couldn't we close this issue?

**Comment by angelozerr** [comment]
The language configuration was implemented for autoclose but it misses other feature like matching bracket https://github.com/eclipse/tm4e/issues/141 and other (I don't remember which features). We can close this issue and creates news for each missing features.
