### ISSUE TITLE
Make bottom panel in TextMate Theme preference page resizable

### ISSUE THREAD

**Issue by PhaserEditor2D** [eclipse/tm4e#133]
Hi,

The preference page at `TextMate > Theme`  is ok but when you maximize it you cannot resize the bottom panel (the one with the "Preview with grammar" parameter). I think is better if it use a SashForm:

![image](https://user-images.githubusercontent.com/12187299/29891522-5bc8189a-8d99-11e7-8350-5ef9258567e0.png)

**Comment by angelozerr** [comment]
Any PR are welcome!

**Comment by boniatillo-com** [comment]
Yes I have to setup the dev environment.

**Comment by sebthom** [comment]
Fixed by #406
