### ISSUE TITLE
Code marked as comment due to Umlauts

### ISSUE THREAD

**Issue by NielsNet** [eclipse/tm4e#134]
There seems to bee an issue with Textmate and umlauts.  
As shown in the issue angelozerr/typescript.java#203 as soon as two or more letters with an umlaut are used the following lines of code are marked as comment even though they should not.  
The following screenshot shows different cases where the behaviour appears.
![grafik](https://user-images.githubusercontent.com/30441612/29863247-5a355f4e-8d6f-11e7-9879-abd29af604ca.png)

**Comment by angelozerr** [comment]
I'm not sure, but perhaps problem comes from that tm4e doesn't support onigurama with UTF-16 (see ignored tests at https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.core.tests/src/main/java/org/eclipse/tm4e/core/grammar/GrammarSuiteTest.java#L44)

I think we should try to implement ConvertUtf16OffsetToUtf8 https://github.com/atom/node-oniguruma/blob/master/src/onig-searcher.cc#L4 in Java at https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.core/src/main/java/org/eclipse/tm4e/core/internal/oniguruma/OnigSearcher.java

Any PR are welcome!

**Comment by fabioz** [comment]
I already have some utilities for converting to/from bytes/multibyte I used in LiClipseText... (https://github.com/fabioz/LiClipseText/blob/master/plugins/org.brainwy.liclipsetext.editor/src/org/brainwy/liclipsetext/editor/partitioning/Utf8WithCharLen.java).

I'll take a look on porting them to `OnigString` (but will leave it up to you to where to place the calls, because it's not just convert one way, the result has to be converted back too...).

Maybe better would be just using always utf-8 internally and convert just the final result? Anyway, will provide a pull request for the conversions shortly, but will leave it up to you where to do the `convertUtf16OffsetToUtf8` and `convertUtf8OffsetToUtf16` calls.

**Comment by angelozerr** [comment]
@NielsNet could you reinstall http://download.eclipse.org/tm4e/snapshots/ and tell me if it fixes your problem. Thanks!

**Comment by fabioz** [comment]
@angelozerr With this change I have the same behavior I had with the approach I was using which just used everything with utf-8 offsets internally and just converting the final result from utf-16 to utf-8.

(i.e.: https://github.com/fabioz/LiClipseText/commit/1d8f88c82676d30edf35b1ef8a70803df3f2681e -- the interesting bit is Token.java and Grammar.java -- mainly, no conversion is needed internally and just the final result is converted).

So not sure... I must say I'm more inclined toward the patch which keeps everything utf-8 internally and just changes offsets when returning to grammar callers (it should be a bit faster as it doesn't have to convert all the time internally which may happen more often and makes internal handling simpler as everything is utf-8 internally as oniguruma has to work on bytes anyways).

If you want I can provide a patch for that...

**Comment by angelozerr** [comment]
@fabioz I have tried to translate node onigurama code and it seems it fixes this issue and https://github.com/eclipse/tm4e/issues/136 (I have only tested in Windows OS).

Im' waiting for users feedback to know if it fixes encoding problem with other OS.

> If you want I can provide a patch for that...

I'm aware with any patch if it improves performance and fixes any problem.

Please note that I would like to consume tokenizeLine2  https://github.com/eclipse/tm4e/issues/38 like VSCode does but for you it will change nothing if you wish to use again tokenizeLine

**Comment by angelozerr** [comment]
@NielsNet please try to reinstall typescript.java http://oss.opensagres.fr/typescript.ide/snapshots/ which install last version of tm4e

**Comment by NielsNet** [comment]
The problem is partally gone:
![image](https://user-images.githubusercontent.com/30441612/31963988-dedd8da2-b902-11e7-8996-e4ba03ffcdf8.png)
However:
![image](https://user-images.githubusercontent.com/30441612/31964049-0b58faba-b903-11e7-9986-de4605adf15c.png)
![image](https://user-images.githubusercontent.com/30441612/31964068-1ae8ac78-b903-11e7-89cb-257773c65f49.png)

**Comment by Omcsesz** [comment]
@angelozerr After installing the latest version of typescript.java, the problem is gone:
![kep](https://user-images.githubusercontent.com/1839739/162329077-5de02952-fdc9-4558-be60-d49191ac9023.png)
