### ISSUE TITLE
Difference between vscode and tm4e for less / scss / vue files

### ISSUE THREAD

**Issue by jabby** [eclipse/tm4e#135]
Hello, 

I am working with bluesky which is based on tm4e and lsp4e. I notice some differences on syntax coloring between vscode and eclipse. I used the textmate grammar for scss and less file from vscode.

Here is the comparison for less file.
![capture d ecran de 2017-09-04 14-34-31](https://user-images.githubusercontent.com/1883932/30026818-defb7dea-917e-11e7-8190-ec6f90595f51.png)

And now for scss file.

![capture d ecran de 2017-09-04 14-40-21](https://user-images.githubusercontent.com/1883932/30026855-feda1d06-917e-11e7-91b0-51eb8a03dc00.png)

Thanks a lot for the project.

**Comment by angelozerr** [comment]
Please share your CSS sample files. If you open the file the fisrt time (without doing changes), have you this problem?

**Comment by jabby** [comment]
Here are my files : 
[style-files.zip](https://github.com/eclipse/tm4e/files/1274755/style-files.zip)

For vue file you can use my version of bluesky https://github.com/jabby/eclipse-bluesky
In vscode the plugin to install is [vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur)

**Comment by angelozerr** [comment]
@jabby I think the problem is because bluesky is using https://github.com/angelozerr/eclipse-bluesky/blob/master/org.eclipse.bluesky/grammars/css/css.plist although it should use the same grammar than VSCode https://github.com/Microsoft/vscode/blob/master/extensions/css/syntaxes/css.tmLanguage.json 

Please test and create an issue at bluesky if needed. Thanks!

**Comment by jabby** [comment]
Ok I understand there was an update in January about the css grammar. So I tried with the new version (css.tmLanguage,json) but the problem is not solved. 
I don't think it's only a bluesky issue. 

I would like to solve the problem and create a pull request with less / scss and vuejs support in bluesky. You can see an updated version of bluesky here : https://github.com/jabby/eclipse-bluesky

**Comment by angelozerr** [comment]
@jabby I have done a fix. Please tell me if it fixes your problem. Thanks!

**Comment by jabby** [comment]
With your fix, the problem is not gone.

**Comment by angelozerr** [comment]
Could you please tell me problems please. With your todo.css, I have that:

![image](https://user-images.githubusercontent.com/1932211/30084332-3ee8e7ba-9292-11e7-97ec-a980e52ba1b8.png)

**Comment by jabby** [comment]
As the title indicates, the problem is about less / scss / vue files. CSS file are OK.

**Comment by angelozerr** [comment]
I have added a CSS rule for entity.name.tag.css. Are there other problems?

**Comment by angelozerr** [comment]
@jabby could you tell me if my last commit fixes your problem please? Thanks!

**Comment by jabby** [comment]
It's ok now. I updated my workspace with latests version of tm4e and eclipse-bluesky.

Thanks a lot.
