### ISSUE TITLE
Language configuration doesn't work in bluesky

### ISSUE THREAD

**Issue by jabby** [eclipse/tm4e#138]
Like I said in https://github.com/mickaelistria/eclipse-bluesky/pull/46#issuecomment-328106402 the closing character doesn't appear when I tried the latest source of eclipse bluesky

I tried on json file and css file and I can't configure the behaviour for scss and less file.

**Comment by angelozerr** [comment]
Have you org.eclipse.ui.genericeditor.autoEditStrategies which is used at https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.languageconfiguration/plugin.xml#L21

**Comment by jabby** [comment]
You're right. I don't have latest version of Generic Editor so I disable this extension point in org.eclipse.tm4e.languageconfiguration. I didn't remember.

Sorry for disturbing you :(

Can you point me to the right git repository ? Thanks.
