### ISSUE TITLE
Register Language Configuration with Preferences

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#139]
Register Language Configuration with Preferences

**Comment by angelozerr** [comment]
@mickaelistria today with that:

![image](https://user-images.githubusercontent.com/1932211/30220876-7ed1de1e-94c1-11e7-9ce1-a2b8bf546fe1.png)

I would like add a `Language Configuration` entry, I though do that inside `TextMate`  entry, but I'm not sure? Having a `Language Configuration` entry in the root doesn't please me.

Have you an idea?

**Comment by mickaelistria** [comment]
I think having it under TextMate makes sense.

**Comment by angelozerr** [comment]
> I think having it under TextMate makes sense.

Ok thanks @mickaelistria

**Comment by LucasBullen** [comment]
Heads up, I am working on this task as it is required for Corrosion.

**Comment by LucasBullen** [comment]
PR opened at https://github.com/eclipse/tm4e/pull/164
