### ISSUE TITLE
Who is using tm4e?

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#140]
@mickaelistria @mniewrzal I have added a new section `Who is using tm4e?` in the readme https://github.com/eclipse/tm4e/#who-is-using-tm4e don't hesitate to add other projects which could use tm4e. Thanks!

**Comment by fabioz** [comment]
LiClipseText: http://www.liclipse.com/text/ is using tm4e.core ;)

**Comment by angelozerr** [comment]
> LiClipseText: http://www.liclipse.com/text/ is using tm4e.core ;)

That's cool:) @fabioz  Could you do a PR to update README please. Thanks!

**Comment by fabioz** [comment]
Sure... ended up adding it to the pull request I had related to the infinite recursion I had opened already (https://github.com/eclipse/tm4e/pull/145) -- it's in a separate commit, so, hope it's Ok.
