### ISSUE TITLE
Matching bracket support with language configuration

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#141]
Matching bracket support with language configuration

**Comment by Boereck** [comment]
Is this issue done, now that #166 is merged?

**Comment by angelozerr** [comment]
@Boereck it works today, but I would liek to improve it https://github.com/eclipse/tm4e/issues/169

**Comment by norru** [comment]
@angelozerr I don't see this working in the editor, am I missing anything (I've got latest snapshots of pretty much everything).

**Comment by mickaelistria** [comment]
This was implemented some time ago.
