### ISSUE TITLE
Some issues with preferences

### ISSUE THREAD

**Issue by mniewrzal** [eclipse/tm4e#143]
See screenshots.
![screenshot from 2017-09-11 12-31-36](https://user-images.githubusercontent.com/7313031/30270530-2ccbe1e0-96ed-11e7-9241-3011fb9367b2.png)
![screenshot from 2017-09-11 12-31-26](https://user-images.githubusercontent.com/7313031/30270529-2ccbd790-96ed-11e7-98bd-bd9833192108.png)

**Comment by angelozerr** [comment]
@mniewrzal for Language Configuration, it's normal. I must develop it.
