### ISSUE TITLE
Advice wanted on a tm4e based project

### ISSUE THREAD

**Issue by am2605** [eclipse/tm4e#148]
Hello,

I'm trying to start up a project that will use the TextMate grammar for the CFML (ColdFusion) programming language.  My attempt at this can be found here:

https://github.com/am2605/cfml4e

Unfortunately a bit of a n00b at Eclipse Plugins and I'm having a few issues which I was hoping I might be able to get a bit of assistance with.

The two issues I'm having are that although my language seems to have registered correctly, my .cfm and .cfc files seem to only open with the "Text Editor", and I have to right click them and open them with "Generic Text Editor" before I see any highlighting.

I know I can manually add an association, but I thought that this:

`   <extension
         point="org.eclipse.ui.editors">
      <editorContentTypeBinding
            contentTypeId="com.abmyers.cfml4e.cfml"
            editorId="org.eclipse.ui.genericeditor.GenericEditor">
      </editorContentTypeBinding>
   </extension>`

Would have done this for me?

Secondly, I have a language configuration like this:

`   <extension
         point="org.eclipse.tm4e.languageconfiguration.languageConfigurations">
      <languageConfiguration
            contentTypeId="com.abmyers.cfml4e.cfml"
            path="language-configurations/cfml.language-configuration.json">
      </languageConfiguration>
   </extension>
   	  `

But I'm not seeing any auto-completion of double quotes, parens and braces, which I was expecting.  Am I right to expect this?

My environment is:

Eclipse for RCP and RAP Developers
Version: Oxygen.1a Release (4.7.1a)
Build id: 20171005-1200
(Windows 10, 64 bit)

**Comment by am2605** [comment]
To answer my own question - I hadn’t declared genericeditor as a dependency on my plugin.  I think this was necessary in order to pull in the latest version.  Seems ok now

**Comment by am2605** [comment]
Sorry to re-open this, but I'm still having problems getting my languageConfiguration recognised.  Is there anything I need to do other than adding the extension point in the plugin.xml?

I can't see it under Preferences -> Text Mate -> Language Configurations either.  It doesn't even look like there's an option to add one?

![image](https://user-images.githubusercontent.com/119977/40161437-19de2f5a-59f4-11e8-957c-d5268178e9d4.png)

**Comment by angelozerr** [comment]
> I can't see it under Preferences -> Text Mate -> Language Configurations either. It doesn't even look like there's an option to add one?

It's because https://github.com/eclipse/tm4e/issues/139 is not finished.

Today language configuration supports `autoClosingPairs`.. I think your language configuration is well registred.

 * so if you type `{`, it should autoclose with `{}`
 * if you go inside `{}` and type enter, it should indent correctly and you should have:

```
{
      | // the cursor should be located here.
}
```

Please create issues for missing features like https://github.com/eclipse/tm4e/issues/141
