### ISSUE TITLE
Paste issue with trailing newline

### ISSUE THREAD

**Issue by creckord** [eclipse/tm4e#150]
After installing TM4E, the Generic Editor has an issue with pasting text, even for files that are not associated with any TextMate grammars.

When pasting text that has a trailing newline (both Windows CRLF and Unix LF style), only an empty new line is inserted. Pasting the same text without the trailing newline inserts the whole text as expected.

There is nothing in the Eclipse logs (or on stdout) indicating an error.

TM4E version: 0.1.0.201709192210
Generic Editor version: org.eclipse.ui.genericeditor 1.1.0.v20171128-0922

**Comment by angelozerr** [comment]
Is it possible for you to create a little video with your problem please. Thanks!

**Comment by creckord** [comment]
Sure, here you go: https://youtu.be/puJbFGV_yTM

**Comment by angelozerr** [comment]
@creckord thanks for your demo. Could you reinstall and tell me if it works better? Thanks!

**Comment by creckord** [comment]
Yes, that fixed it. Thanks!

**Comment by angelozerr** [comment]
Thanks @creckord for reporting this issue.
