### ISSUE TITLE
TM4E not available in Photon release train

### ISSUE THREAD

**Issue by akurtakov** [eclipse/tm4e#153]
TM4E feature is not available in Photon release train. As long as it's not in the release train projects depending on it have to mirror its bundles in their p2 sites which is too much effort for easy usage of tm4e.

**Comment by angelozerr** [comment]
@mickaelistria @akurtakov could you help me with this issue?

**Comment by mickaelistria** [comment]
This was done some time ago. aCute and Corrosion both require tm4e and can resolve it from SimREl.
