### ISSUE TITLE
TMPresentationReconciler's textChanged using wrong viewer when mulitple are open

### ISSUE THREAD

**Issue by LucasBullen** [eclipse/tm4e#156]
Using tm4e within [Eclipse Corrosion](https://github.com/eclipse/corrosion) and after using for a portion of time with multiple editors open eventually text colour styling is lost.

This is caused by an Invalid Arguments error thrown from `StyledText.getStyleRangeAtOffset()` because within `TMPresentationReconciler's textChanged` the `e.getOffset()` is the correct offset, but the `viewer` is for a different editor.

Have not been able to track down how the `viewer` gets switched or create a test case, but is this common with anyone else? Any causes you can think of?

Closing the editor and re-opening it fixes the problem.

**Comment by angelozerr** [comment]
I'm afaraid that you are the first who has this problem @LucasBullen -(

If you can fix it, any contribution are welcome!

**Comment by LucasBullen** [comment]
More research with a test case using Corrosion and aCute, both implementing tm4e, for this example, but will might work with any tm4e implementation:
 - Open two files
 - Make each file only one line that would contain colouring from tm4e syntax
 - Add a new line to the second file that contains colouring
 - Add a new line to the first file that also contains colouring
### Expected
 - New line is coloured correctly
### Actual
 - New line and all other changes to this file are not coloured  

![demo-of-tm4e-bug](https://user-images.githubusercontent.com/10255066/38332223-76539b96-3823-11e8-8e1b-237668f5ae70.gif)

@angelozerr are you able to replicate this issue elsewhere?

**Comment by angelozerr** [comment]
Good catch @LucasBullen ! It seems the problem is the use of TMPresentationReconciler with genereic editor. When you open two editor with Genereic Editor the instance of TMPresentationReconciler  are the same, is it a normal behaviour?

**Comment by LucasBullen** [comment]
You are right, this is an issue with the generic editor only creating one instance of the reconciler, and lucky enough the last patch which was to fix something else fixes this issue as well (https://git.eclipse.org/r/#/c/119994/) now the GE will create a different instances of the presentation reconciler for each editor. So in Photon this won't be an issue. Thanks for the help.

**Comment by angelozerr** [comment]
> Thanks for the help.

You are welcome! Thanks for your demo.
