### ISSUE TITLE
a handler to toggle comments using language-configuration.json

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#159]
Language-configuration.json contains a description of comment blocks/line. We should use it in TM4E to create a handler (and maybe a command, but having a command in Eclipse Platform would be better) for Toggle Comment on any language which is bound to a language-configuration.json containing those informations.

**Comment by angelozerr** [comment]
Done. Thanks @LucasBullen for your great contribution! We need to update wiki to specify key commands to use.

**Comment by mickaelistria** [comment]
I think we can close this issue then. Thanks @LucasBullen
