### ISSUE TITLE
Syntax highlighting of a SourceViewer

### ISSUE THREAD

**Issue by PhaserEditor2D** [eclipse/tm4e#161]
Hi,

I need to use TM grammas on a source viewer. I was looking in code and there is a TMViewer, but it is inside an internal package so I cannot use it. 

What can I do?

My real issue is to have syntax coloring inside a dialog (not an editor):

![image](https://user-images.githubusercontent.com/12187299/41869348-b51b0cd0-7886-11e8-9272-c54552599524.png)

**Comment by PhaserEditor2D** [comment]
For the moment I just "cloned" the `TMViewer` code into a `TMViewer2` and I am using that one. But I guess it would be great if the `TMViewer` is moved to a public package.

**Comment by mickaelistria** [comment]
For the generic editor, we can simply add the TMPresentationReconcilier to the viewer. Have you tried just something like
```java
ISourceViewer myViewer = ...; // your already existing viewer
TMPresentationReconciler textmate = new TMPresentationReconciler();
textmate.install(myViewer);
myViewer.addDisposeListener(() -> textmate.uninstall(myViewer));
```
?

**Comment by PhaserEditor2D** [comment]
Yes, the installation of the `TMPresentationReconciler` works. I will use it. Thanks.
