### ISSUE TITLE
Add language specific on enter rules

### ISSUE THREAD

**Issue by LucasBullen** [eclipse/tm4e#168]
VSCode currently has the onEnterRules added through typeScript. We should either solve the regex in json issue or add an extension point to allow consumers to add onEnterRules.

**Comment by LucasBullen** [comment]
Making good progress on an extension point implementation, however ran into a problem storing strings that start/end with whitespace:
```
<onEnterRule
         beforeText="^\s*\/{3}.*$">
   <enterAction
         indentAction="None"
         appendText="/// ">
   </enterAction>
</onEnterRule>
```
The space after the `///` is lost and `&#160;` causes a lot of troubles while `\u0020` doesn't get converted and is inserted as is. Same issue if I have the appendText is added as the value of the element:
```
<onEnterRule
         beforeText="^\s*\/{3}.*$">
   <enterAction
         indentAction="None">///  </enterAction>
</onEnterRule>
```
Here the space is still lost and adding the `xml:space` attribute doesn't have an affect.
@mickaelistria any thoughts?

**Comment by LucasBullen** [comment]
Ok ya just ignore me. When testing adding a double escape for back slashes (the cause of the errors in json) it wasn't working for some reason. Now it is working so that is definitely the better strategy.

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/tm4e/pull/170
