### ISSUE TITLE
Comment support doesn't work on Windows OS + CSS Language Server

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#172]
@LucasBullen I create this issue, because your work on comment support doesn't work on a given context : 

 * Windows OS where Ctrl+Shift+/ doesn't work (in Windows OS I must key on Shift to have '/'). I have the same problem with JDT. Because of this problem, I can never call block comment which is only supported by CSS and XML, HTML language.
 * CSS Language Server which defines only block comment.

1) Key command problem 

So to fix the key command problem, I suggest to do like WTP:

 * for adding/removing block comment, WTP does like this:

```xml
<key
	sequence="M1+M2+/"
	contextId="org.eclipse.wst.sse.ui.structuredTextEditorScope"
	commandId="org.eclipse.wst.sse.ui.add.block.comment"
	schemeId="org.eclipse.ui.defaultAcceleratorConfiguration">
</key>
<key
	sequence="M1+/"
	contextId="org.eclipse.wst.sse.ui.structuredTextEditorScope"
	commandId="org.eclipse.wst.sse.ui.add.block.comment"
	schemeId="org.eclipse.ui.defaultAcceleratorConfiguration"
	platform="carbon">
</key>
<key
	sequence="M1+M2+\"
	contextId="org.eclipse.wst.sse.ui.structuredTextEditorScope"
	commandId="org.eclipse.wst.sse.ui.remove.block.comment"
	schemeId="org.eclipse.ui.defaultAcceleratorConfiguration">
</key>
<key
	sequence="M1+\"
	contextId="org.eclipse.wst.sse.ui.structuredTextEditorScope"
	commandId="org.eclipse.wst.sse.ui.remove.block.comment"
	schemeId="org.eclipse.ui.defaultAcceleratorConfiguration"
	platform="carbon">
</key>
```
 * for adding/removing line comment, WTP does like this:

```xml
<key
	sequence="M1+M2+C"
	contextId="org.eclipse.wst.sse.ui.structuredTextEditorScope"
	commandId="org.eclipse.wst.sse.ui.toggle.comment"
	schemeId="org.eclipse.ui.defaultAcceleratorConfiguration">
</key>
```
Are you OK @LucasBullen, @mickaelistria to do that? It will work on any OS.

2)  CSS Language Server which defines only block comment.

As 1) doesn't work on Windows OS, I cannot commment my CSS, XML, HTML files. But even if 1) is fixed, it should be cool to comment lines even if it is not defined by using block comment info.

@LucasBullen, @mickaelistria are you OK with that? 

If you are OK @LucasBullen is there any chance that you could work on this issue?

**Comment by angelozerr** [comment]
> Created #173 to solve problem 1)

Thanks, I will review it ASAP.

> Are you saying if there isn't a line comment defined that it should take the block comment and comment the full line?

Yes, I think. Please try with vscode html file to see her behaviour (line comment is not defined)

**Comment by angelozerr** [comment]
@LucasBullen I have improved a little your work to avoid updating teh document if line/block comment is not defined in https://github.com/eclipse/tm4e/commit/31cf888cb44c74e89932b2f2bb7c7042266d0ae9

Please check that I have not broken something. Thanks!

**Comment by sebthom** [comment]
@angelozerr is there anything actionable left to be done for this issue?

**Comment by sebthom** [comment]
Ok, I am going to close this for now then.
