### ISSUE TITLE
Contextual menu for comments commands

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#174]
It should be cool to have comments commands in contextual menu (like WTP or JDT)

![image](https://user-images.githubusercontent.com/1932211/44549826-9a0bee80-a722-11e8-9c70-86c914aa5d8e.png)

We can see in this case the key binding to use in the menu.

@LucasBullen is there any chance that you work on this issue?

**Comment by mickaelistria** [comment]
The source menu is contributed by JDT or WTP. Should we first add a "Source" menu definition to the Generic Editor?

**Comment by angelozerr** [comment]
> Should we first add a "Source" menu definition to the Generic Editor?

Perhaps yes?

**Comment by sebthom** [comment]
Implemented via #421
