### ISSUE TITLE
TM4E overrides manually defined editor colors

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#176]
I've set a background color to my text editors to something that's a bit softer than plain white. I've done it through Preferences > General > Editors > Text Editors changing the background color.
When I open the Generic Editor without a TM4E contributing, all is fine, I get the background color I configured. Whenever I open it on a file that has a TextMate grammar associated and TM4E enabled for it, the color is restored to plain white, reducing my comfort and making this behavior feel a bit buggy.

In case user overrides the setting, it should most likely be honored by TM4E. Same goes with the default foreground color.

**Comment by jabby** [comment]
IIUC, the priority for colors in text editors should be 

1. User definition in Text Editor
2. Textmate grammar if there is no user definition
3. Eclipse Theme if there is nothing else

I didn't look into TM4E code base but I think we should have a reconciler / aggregator for all this definition of color.

**Comment by mickaelistria** [comment]
I could verify that at least the background color is kept and was happy with the result. Enough to close this ticket IMO.
