### ISSUE TITLE
Custom grammar files cannot be removed

### ISSUE THREAD

**Issue by norru** [eclipse/tm4e#177]
I have added a custom tmLanguage grammar. When the added grammar file is selected, the "Remove..." button is greyed out making the removal impossible.

![preferences _016](https://user-images.githubusercontent.com/889291/45257997-8d84c880-b3a7-11e8-8376-6c5399c75c4a.png)

**Comment by norru** [comment]
Duplicate of  #149?

**Comment by angelozerr** [comment]
> Duplicate of #149?

Indeed, I have not implemented it.
