### ISSUE TITLE
Possible NPE in LanguageConfigurationDefinition

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#178]
See https://github.com/eclipse/corrosion/issues/131 . It's possible that parsing fails and the configuration is null. This cascade to NPE downstream and breaks the editor.

**Comment by mickaelistria** [comment]
Fix prevents from NPE.

**Comment by angelozerr** [comment]
Thanks @mickaelistria !

**Comment by norru** [comment]
The error still occurs, it's just being caught.

Just a thoght: I'm seeing this on Linux, could it be that there is a case-sensitve path that is being referenced incorrectly?

![selection_071](https://user-images.githubusercontent.com/889291/45543454-69444400-b80c-11e8-80ff-78d744d9ab79.png)

**Comment by norru** [comment]
Is the file supposed do be in the plugin jar?

```
jar tvf org.eclipse.corrosion_0.1.0.201809121453.jar  | grep language-configurations
```

**Comment by mickaelistria** [comment]
The NPE you see is another flavor (less critical one).
The hint about the missing file is great, let's keep chatting about it in https://github.com/eclipse/corrosion/issues/124
