### ISSUE TITLE
Bracket matching highlight status?

### ISSUE THREAD

**Issue by norru** [eclipse/tm4e#179]
In *Language configurations* there is an option to "Enable matching brackets" which has no visible effect in the editor.

When enabled, it should be able to highlight the matching open/closed level of parentheses near the cursor:

![selection_019](https://user-images.githubusercontent.com/889291/45574782-0d5bd880-b869-11e8-8751-5f2976f68d0b.png)
(pretty much a standard feature of most code editors).

**Comment by norru** [comment]
Diplicate of https://github.com/eclipse/tm4e/issues/141?

**Comment by norru** [comment]
Never mind, just got latest *everything* (snaps) and it works, many thanks!

**Comment by norru** [comment]
Actually, I spoke too soon - I've done the same on another machine and it doesn't work.

**Comment by norru** [comment]
It does appear that this feature requires the following:
```
Eclipse IDE for Rust Developers	4.9.0.20180906-1225	epp.package.rust	Eclipse Packaging Project
```

Which is not included in the default Photon fr Rust download, but appears to be available from http://download.eclipse.org/releases/2018-09?

**Comment by angelozerr** [comment]
@norru matching bracket requires a nes feature of Genereic Editor https://bugs.eclipse.org/bugs/show_bug.cgi?id=538111

**Comment by norru** [comment]
I confirm it works wit Eclipse 4.9.0
