### ISSUE TITLE
[regression?] Code folding gutter disappeared?

### ISSUE THREAD

**Issue by norru** [eclipse/tm4e#181]
Hi,

I'm running latest snapshot of Eclipse 2018-09, tm4e, lsp4e and corrosion to test progress (a life on the edge, I know!).

After an "upgrade all", the code folding feature, which was working on the previous update, has disappeared again.

**Comment by angelozerr** [comment]
TM4E doesn't provide code folding features. I don't know corrosion but folding is managed:

 * with the corrosion Language Server (LSP4e)
 * if the corrosion Language Server doesn't provide foldingRanges, folding is managed with genereic editor

In other words problems comes from Generic Editor or LSP4e.

**Comment by mickaelistria** [comment]
@norru please report it to Corrosion and I'll investigate which one may be the culprit.

**Comment by norru** [comment]
Sounds good.

**Comment by norru** [comment]
https://github.com/eclipse/corrosion/issues/137
