### ISSUE TITLE
TextMate/GenericTextEditor overlapping functionality

### ISSUE THREAD

**Issue by norru** [eclipse/tm4e#183]
@angelozerr:

TM4A allows opening documents in either

- TextMate (with incomplete functionality)
- GenericTextEditor

I seem to understand that the former is redundant and perhaps should be removed.

**Comment by mickaelistria** [comment]
I agree. The TextMate editor might make sense in some rare cases but shouldn't really leak in the usual IDE. Maybe it would better be in a separate plugin, which wouldn't be included by default when installing Corrosion or others.

**Comment by norru** [comment]
@mickaelistria @angelozerr ?

**Comment by angelozerr** [comment]
@norru I have removed TextMate Editor in https://github.com/eclipse/tm4e/commit/463b92fe24c6c9f65756e22c40bd32bb1a2fd2ba

I close the issue.
