### ISSUE TITLE
Implementing TextMate support for a DSL created using Xtext

### ISSUE THREAD

**Issue by SharkJ** [eclipse/tm4e#187]
Hi,
I have a simple DSL made using Xtext in Eclipse with the following grammar : -
```
grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model:
    greetings+=Greeting*;

Greeting:
    'Hello' name=ID '!';
```
When I run this as a plugin in Eclipse, it works fine with syntax highlighting. However, when I tried to run it as a Language Server in Eclipse Che, the syntax highlighting service did not work. 
Is it possible to overcome this problem by implementing TextMate? How should it be done?

Thanks!

**Comment by mickaelistria** [comment]
This project (TM4E) is not related to Eclipse Che nor to Language Servers nor to XText. I suggest you ask this question to the Eclipse Che and or Eclipse XText user/developer support channels.

I think a good thing to do for XText would be to be able to generate some textmate grammars for syntax highlighting. It's currently generating Eclipse IDE specific syntax highlighting services that are not based on TextMate and not portable to other IDEs.
But this is a XText-related comment and you should ask for this in the xtext github repo.
