### ISSUE TITLE
Pressing '(' closes enclosing parentheses instead of adding '(' 

### ISSUE THREAD

**Issue by theDragonFire** [eclipse/tm4e#194]
I have code like this:
```rust
foo(String::from[cursor is here])
```
and I press the '(' key to open a pair of parentheses, expecting this to be the result:
```rust
foo(String::from([cursor is here]))
```
Instead, it closes the outer parentheses, with the result being this:
```rust
foo(String::from)[cursor is here]
```
Is there some way to change this? It slows me down to have to delete the closing parentheses, then add them back in.

Also, it seems that this should happen when you press ')', but it doesn't.

**Comment by mickaelistria** [comment]
This should now be fixed. To take advantage of the fix, just install latest snapshot in your IDE (see https://github.com/eclipse/tm4e#install )

**Comment by theDragonFire** [comment]
Thanks for the improvement! However, I may not have been clear when I said 

> Also, it seems that this should happen when you press ')', but it doesn't.

Based on the test you wrote,
```
// ignore already opened
text.setText("()");
text.replaceTextRange(0, 0, "(");
Assert.assertEquals("()", text.getText());
Assert.assertEquals(1, text.getSelection().x);
```
it seems that you thought that I meant something like this:
```
// original code
[cursor is here]()
// user presses '('
([cursor is here])
```
Instead what I meant is something like this:
```
// original code
([cursor is here])
// user presses ')'
()[cursor is here]
```
Based on the test written above (I haven't looked at the full code base), I think that this test would suffice
```
text.setText("()");
text.replaceTextRange(1, 0, ")");
Assert.assertEquals("()", text.getText());
Assert.assertEquals(2, text.getSelection().x);
```
Anyway, whatever you can do is great. What you've done already is fantastic. Thanks for your time.

**Comment by mickaelistria** [comment]
I've mainly focused on the title and example. The case of a closing pair is already reported in #192 .
I'll try to work on it later, but I've got a bunch of other hot topics filling my todo-list these days; so if you or anyone else want to continue this work and cover this use-case as part of #192, that'd be very welcome.

**Comment by theDragonFire** [comment]
I would love to help contribute, but I am not familiar with how the repository is structured, what tools are being used, and just how to contribute code in general. Is there somewhere where I could get more information about that?

**Comment by mickaelistria** [comment]
We should work on a CONTRIBUTING.md, if you feel interested in writing one, please start it and I'll gladly help by answering your questions..
Developing TM4E requires to use the Eclipse IDE with Eclipse Plugin Development Environment (PDE) available. Then, for this issue, you open the `org.eclipse.tm4e.languageconfiguration` and `org.eclipse.tm4e.languageconfiguration.tests` projects in your IDE, you edit the test with the failing scenario, right-click > Run As > Junit Plugin Test to verify it fails, make the fix in LanguageConfigurationAutoEditStrategy.java, and run test again to verify is passes.
