### ISSUE TITLE
Brackets closing is completely broken

### ISSUE THREAD

**Issue by norru** [eclipse/tm4e#197]
In latest Corrosion + TM4E Snapshot (hopefully not released) I cannot reliably type "(" and ")" no matter what the Autoclose does. Open parentheses cannot be closed.

Easy repro:

Type `()`, backspace to delete the last `)` then type `)` again.

Result:

The cursor moves but the `)` never appears.

Expected result:

The `)` is typed so the parentheses match

Versions:
```
org.eclipse.tm4e.core (0.3.1.201901071439) "TextMate support in Java" [Resolved]
org.eclipse.tm4e.languageconfiguration (0.3.1.201901081109) "TextMate support in Eclipse IDE - Language Configurations" [Resolved]
org.eclipse.tm4e.markdown (0.3.1.201901071439) "TextMate support in Eclipse IDE - Markdown" [Starting]
org.eclipse.tm4e.registry (0.3.1.201901071439) "TextMate support in Eclipse IDE - Registry management" [Resolved]
org.eclipse.tm4e.samples (0.3.1.201901071439) "TextMate support in Eclipse IDE - Samples" [Resolved]
org.eclipse.tm4e.ui (0.3.1.201901071439) "TextMate support in Eclipse IDE - UI" [Active]
org.eclipse.tm4e.ui.editor (0.2.0.201809031154) "TextMate support in Eclipse IDE - Simple TextMate Editor" [Starting]
```

**Comment by mickaelistria** [comment]
This should now be fixed with https://github.com/eclipse/tm4e/commit/f754faba3cac3f36c2927b0908747d18b44ab46b . TM4E was rebuilt and a new snapshot is avaiable.

**Comment by norru** [comment]
Hi @mickaelistria, just got latest and this seems fixed, many thanks for the super-quick response!

I'll keep testing throughout the day and report any further issues.

**Comment by mickaelistria** [comment]
> many thanks for the super-quick response!

Twice more thanks for you super-quick and well described feedback!
