### ISSUE TITLE
Can't get Generic editor to use provided Textmate grammars

### ISSUE THREAD

**Issue by fbricon** [eclipse/tm4e#202]
Using tm4e  0.3.2.201901202056, I installed the Kotlin TM grammar from https://github.com/mathiasfrohlich/vscode-kotlin/blob/master/syntaxes/Kotlin.tmLanguage, and the Groovy grammar from https://github.com/textmate/groovy.tmbundle/blob/master/Syntaxes/Groovy.tmLanguage. Highlighting works in the tm4e preview panel, but not when opening the files with the generic editor. See for kotlin:
![Apr-07-2019 11-43-11](https://user-images.githubusercontent.com/148698/55686251-caf50880-592c-11e9-90f0-ffe13e2c3b8c.gif)

**Comment by mickaelistria** [comment]
Did you enable the TMPresentationReconcilier for the expected content-types in generic editor? https://github.com/eclipse/aCute/blob/master/org.eclipse.acute/plugin.xml#L72
Did you associate the TextMate grammar/scope with desired content-types? https://github.com/eclipse/aCute/blob/master/org.eclipse.acute/plugin.xml#L59

**Comment by mickaelistria** [comment]
See https://github.com/eclipse/tm4e/wiki/UI

**Comment by fbricon** [comment]
As a simple user, my expectation is that, once tm4e is installed and I provide textmate grammars (I wish a bunch of those were already provided OOTB, or I could discover and install them through some UI at least, but that's another story), it would just work in the generic editor. Anything that requires me to write plugin.xml configuration is a complete no-go, for *me*. So it seems I misunderstood the goal and scope of the project, which is fine, but maybe the readme ought to be clearer.

**Comment by mickaelistria** [comment]
Better workflow for user addition of TextMate grammars would be a nice to have, but it's not really considered as a big factor of success for TM4E nor the IDE. Having only syntax highlighting isn't usually the value we aim to provide, nor the value most users expect in an IDE. If you want Kotlin or Groovy support, then it's better to install the full Kotlin and Groovy plugins. Whether they decide to use TM4E or something else is up to them.
At the moment, TM4E targets plugin developers, not really end-users. This could indeed be improved.

Please re-title the bug to better capture it as an enhancement request.

**Comment by angelozerr** [comment]
> As a simple user, my expectation is that, once tm4e is installed and I provide textmate grammars

I agree with you @fbricon it was my goal when I developed the UI preferences to add user TM grammar. It should work and I think your problem is that you have a content type.  I must find time to debug the problem at https://github.com/eclipse/tm4e/blob/f52ef37e230bd339df145a0b1bf8883e7f67af4c/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/text/TMPresentationReconciler.java#L287

**Comment by mickaelistria** [comment]
The TMPresentationReconcilier is not enabled by default on the Generic Editor. It's up to extenders (providers of grammars) to declare usage of the TMPresentationReconcilier for the Generic Editor for a given content-type in their plugin.xml.
We could have TM4E creating a basic content-type, having TM4E associating Generic Editor and TMPresentationReconcilier for this content-type, and adding TextMate files would automatically read the file extensions and update the content-type with the new extensions so they get updated.
But I do see many things in the overall "Eclipse IDE" story that seems much more profitable to implement.

**Comment by angelozerr** [comment]
> The TMPresentationReconcilier is not enabled by default on the Generic Editor.

Except if it exists a content type which extends `org.eclipse.core.runtime.text`. I have tested with `Kotlin` TM grammar. I have created :

 *  a `Kotlin` content type which extends `org.eclipse.core.runtime.text`
 * bind `Kotlin` content type with `*.kt`

![image](https://user-images.githubusercontent.com/1932211/55782486-ade74380-5aac-11e9-9e32-00a238d3f9c5.png)

 * register TM freemarker grammar (like @fbricon has done)

![image](https://user-images.githubusercontent.com/1932211/55782522-c48d9a80-5aac-11e9-84e6-325aaf715871.png)

and it works:

![image](https://user-images.githubusercontent.com/1932211/55782556-d4a57a00-5aac-11e9-926c-e83320f1fae3.png)

We could improve this workflow by creating a content type (if it doesn't exists) when TM grammar is added.

**Comment by cmoine** [comment]
I think I have found a bug which prevents make it work with user defined content type:
```
        @Override
	public IGrammar getGrammarFor(IContentType[] contentTypes) {
		if (contentTypes == null) {
			return null;
		}
		// Find grammar by content type
		for (IContentType contentType : contentTypes) {
			String scopeName = getScopeNameForContentType(contentType.getId());
			if (scopeName != null) {
				IGrammar grammar = getGrammarForScope(scopeName);
				if (grammar != null) {
					return grammar;
				}
			}
		}
		return null;
	}
```
Can I provide a PR for this ?

**Comment by angelozerr** [comment]
> Can I provide a PR for this ?

Yes please!

**Comment by cmoine** [comment]
https://github.com/eclipse/tm4e/pull/219

**Comment by mickaelistria** [comment]
Fixed thanks to @cmoine 's https://github.com/eclipse/tm4e/commit/b12cba8464b22f7e1a2cc72528b3e2022afe320c
