### ISSUE TITLE
Use standard logging APIs

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#209]
TM4E has implemented its own logging approach. Instead, it should rely on some existing efficient logger APIs.

**Comment by mickaelistria** [comment]
@angelozerr : is there any specific reason for not using a standard logging API? Do you foresee potential issues if we change it?

**Comment by angelozerr** [comment]
As tm4e can be used outside Eclipse IDE, I didn't want to be linked to a logging API. if you wish to use a logging API, please consider that tm4e can be used outside Eclipse IDE (use perhaps java.util.logging API).
