### ISSUE TITLE
java.lang.IllegalArgumentException: Index out of bounds

### ISSUE THREAD

**Issue by lak-proddev** [eclipse/tm4e#213]
IllegalArgumentException while working on dart file.

See log for more details
https://github.com/eclipse/dartboard/issues/91
[Exceptions.txt](https://github.com/eclipse/dartboard/files/3376867/Exceptions.txt)

Stacktrace is different from https://github.com/eclipse/tm4e/issues/99

**Comment by mickaelistria** [comment]
Should be fixed now.
