### ISSUE TITLE
Switch to theme only works once for open editor

### ISSUE THREAD

**Issue by PyvesB** [eclipse/tm4e#220]
Hello,

Using the "Switch to Theme..." menu works the first time but fails on subsequent attempts until the editor is closed and reopened again.

I did a bit of debugging and discovered that this behaviour is caused by this [particular if condition](https://github.com/eclipse/tm4e/blob/5c855d43cf10e3681b8b0c52df71fcd5e898eec7/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/text/TMPresentationReconciler.java#L170). The `forcedTheme` handling was apparently introduced in a390c266c343bfe69519c90d3a6105da9ed5f6fd. The commit message isn't very explanatory, does anyone have more insight on why was this added? Is it still needed now?

Cheers,

Pyves

**Comment by mickaelistria** [comment]
I suggest you just try removing it, test a bit, and if you think it's better, we can merge a PR.

**Comment by mickaelistria** [comment]
FWIW, I plan to release TM4E for 2019-09 on Friday or Monday. I'll make a PR review high priority before that ;)

**Comment by PyvesB** [comment]
> FWIW, I plan to release TM4E for 2019-09 on Friday or Monday. I'll make a PR review high priority before that ;)

Well in that case I'll make submitting the PR high priority!
