### ISSUE TITLE
Add a hotkey to re-trigger manual syntax recoloring after failing on autoformat

### ISSUE THREAD

**Issue by norru** [eclipse/tm4e#226]
https://github.com/eclipse/corrosion/issues/243 and https://github.com/eclipse/tm4e/issues/203 are still not fixed. I infer that they're either too low a priority, or too complex a fix.

Either case, it would reckon that they won't be fixed any time soon but the functionality is still required somehow.

The current workaround is to close an editor and reopen it after every autoformatting, which is too impractical to be used, and pretty much makes the in-editor autoformat pretty much useless.

In order to restore the auto-format functionality we need a workaround so a manual syntax re-coloring is triggered, either on demand (using a hotkey) or "appending" the functionality to the autoformat key.

**Comment by mickaelistria** [comment]
A hotkey would be a workaround, development effort of anyone interested in and able to fix this would be more profitable if invested in actually fixing the issue.
I personally cannot manage to reproduce it in ~99% of cases. If I were able to reproduce it more easily, I'd gladly try to fix it.

**Comment by norru** [comment]
It's now 100% for me in all my files, all my projects on all my machines, fast and slow. All Linux boxes (Ubuntu and Devuan).

The only common denominator is that they tend to be non-trivial projects (several klocs/crate, several 1klocs+ source .rs files).

**Comment by mickaelistria** [comment]
Ok. can you please share such a big rust file you're using and always see it failing? Maybe that will good enough for me to reproduce it.

**Comment by norru** [comment]
Just reproduced at first attempt on https://github.com/itadinanta/rust-oids/blob/master/src/backend/world/gen.rs, which is not even *that* large!

**Comment by norru** [comment]
If you manage to repro, feel free to close this bug and continue on #203 or https://github.com/eclipse/corrosion/issues/243.

**Comment by norru** [comment]
If it helps, I also get this very often when the problem appears:

![Selection_228](https://user-images.githubusercontent.com/889291/65688311-6c4a5500-e05a-11e9-8598-8d483f7b5f26.png)

**Comment by mickaelistria** [comment]
That popup is quite interesting, but it comes from the LS, not from TM4E.
So it's a different issue: the LS may send wrong messages or LSP4E fail at interpreting them properly, but TM4E should still be able to perform correct syntax highlighting independently of that.

**Comment by norru** [comment]
The popup does not appear all the time, just often.

However, this kind of points to a data race if you ask me.

**Comment by PyvesB** [comment]
This happens to me every now and again, it's quite annoying. I'll keep an eye open and see if I can find a good reproducible example next time I bump into this.

**Comment by norru** [comment]
@PyvesB If I had a way to make it happen every now and again rather than every single time, I'd be a happy bunny!

**Comment by norru** [comment]
This is still a requirement. Workaround is still to close/reopen editor.

**Comment by mickaelistria** [comment]
Fixing the bug is the requirement, implementing another workaround isn't ;)

**Comment by mickaelistria** [comment]
To clarify, I'm closing this issue as I think it's not a desired resource allocation from project perspective.

**Comment by norru** [comment]
Fair enough, but the bug is still a real pain in the neck! :)

**Comment by mickaelistria** [comment]
I know, but I really fail at reproducing it. So whoever is more(?) lucky to reproduce it easily can give it a try to a fix. that would be very welcome!

**Comment by norru** [comment]
I know, right? It's baffling that it can't be reproduced on your machine!
