### ISSUE TITLE
Unusual block comment key binding on mac os

### ISSUE THREAD

**Issue by xcariba** [eclipse/tm4e#246]
Hello!
I noticed that block comment binding has unusual binding on mac os - `M1 + \` while in JDT block comment is binded to `M1+M4+\`. In my product line comment is binded to `M1+\` (common binding in other IDE's) and it conflicts on mac os.

**Comment by mickaelistria** [comment]
As https://github.com/eclipse/tm4e/commit/069b1f59d04bed728fc82a785c416f8b5f6ad1ef is merged, I think we can close it. Please try latest snapshots and comment if it has to be reopen.
