### ISSUE TITLE
Themes preference page has many permanently disabled controls

### ISSUE THREAD

**Issue by nitind** [eclipse/tm4e#249]
The "New" and "Remove" buttons on the TextMate Themes preference page never enable, which is unusual because "New" would be expected to always be enabled. In fact, the checkboxes at the bottom are seemingly never enabled, and the preview area never contains text, in contrast to every other text preview area. The preview area should also disable when no theme is selected (or when more than one is selected, which is possible).

The New/Remove button labels are also not antonyms.

**Comment by jabby** [comment]
See also #190

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipse/tm4e/pull/253
