### ISSUE TITLE
Missing sources on simultaneous releases Update Sites

### ISSUE THREAD

**Issue by mdaloia** [eclipse/tm4e#252]
The sources for TM4E are being generated but they are not being included on Eclipse simultaneous releases Update Sites (for example for 2020-06).

This can be seen comparing for example these 2 Update Sites:

https://download.eclipse.org/tm4e/releases/0.4.0/
https://download.eclipse.org/releases/2020-06/

<img alt="Update Sites comparison" src="https://user-images.githubusercontent.com/1738654/90197414-f26fa700-dda4-11ea-9c7c-1a8758089cec.png" width="450">

**Comment by mickaelistria** [comment]
Please submit a patch to SimRel build using Gerrit: https://git.eclipse.org/r/admin/repos/simrel/org.eclipse.simrel.build , it's mostly a matter of adding the .source feature to the tm4e.aggrcon file.

**Comment by mdaloia** [comment]
Thanks Mickael for point out where and how to do it!
Submitted https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/173752

I hope it is ok to just adding the source feature group otherwise let me know and I will change it.

**Comment by mdaloia** [comment]
Closing this issue as it was fixed with commit https://git.eclipse.org/r/plugins/gitiles/simrel/org.eclipse.simrel.build/+/684f4a6386eff6113ed78bbf837e12593b801c15%5E%21/#F0

Available since SimRel 2021-03:
<img alt="Update Sites comparison" src="https://user-images.githubusercontent.com/1738654/112201160-bc25c000-8bee-11eb-976f-a2052682148e.png" width="450">
