### ISSUE TITLE
Editor "foreground color" wrong after saving or losing focus, correct when first applying theme.

### ISSUE THREAD

**Issue by AmigaAbattoir** [eclipse/tm4e#256]
When I'm using WWD in Eclipse 2020-09, the Generic Editor for HTML, JS and JSON and I open files, regular text that should be black is a light grey. 

If I switch themes, the black text appears fine until the file gets saved:
![Screen Shot 2020-09-22 at 9 11 37 AM](https://user-images.githubusercontent.com/6256023/93906324-0e326b00-fcca-11ea-9cd2-8f681d29e0a8.png)

If I switch themes back to Eclipse Dark, everything looks fine:
![Screen Shot 2020-09-22 at 9 11 30 AM](https://user-images.githubusercontent.com/6256023/93906268-fce95e80-fcc9-11ea-9e85-5f3d004f6c19.png)

Hit save and then everything goes grey:

Both screenshots are with the Switch to **Theme... -> Eclipse Dark** selected. I haven't added any themes to under **Preferences -> Textmate -> Theme**

I'm using **General -> Appearance** _Theme_: Dark.

I also have under **Preferences -> General -> Editors -> Text Editors** have different colors for _Appearance color options_
![Screen Shot 2020-09-22 at 10 25 40 AM](https://user-images.githubusercontent.com/6256023/93906334-1094c500-fcca-11ea-98f0-0e1c77d00ee6.png)

(Originally filed under https://github.com/eclipse/wildwebdeveloper/issues/536)

**Comment by AmigaAbattoir** [comment]
@mickaelistria posted a reply https://github.com/eclipse/wildwebdeveloper/issues/536#issuecomment-696807257 and asked to file this here.

> That's a quite confusing setup: the general theme seems dark (according to property page screenshot) and set the background color for the text editor to be white, but the actual background color in your editor screenshot is grey... I think TM4E (which provides the syntax highlighting) gets confused with this configuration, and applies a Dark highlighting while your editor background is mostly light.
This issue should be reported to TM4E, the culprit line is probably https://github.com/eclipse/tm4e/blob/f52ef37e230bd339df145a0b1bf8883e7f67af4c/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/internal/themes/AbstractThemeManager.java#L92 which doesn't take the actual editor background into account but instead relies on not so relevant theme id.

**Comment by mickaelistria** [comment]
Do you confirm that you do use a dark theme with a light color for the text editor?

**Comment by AmigaAbattoir** [comment]
Yes, I'm using the Dark theme for Eclipse, but I am using a _Background color_ of #E6E6E6 and a _Foreground color_ of #141618.

**Comment by mickaelistria** [comment]
I couldn't really change the background color in my IDE with Dark Theme to easily reproduce the issue.
Anyway, I improvised a fix and merged it. Please give a try to https://download.eclipse.org/tm4e/snapshots/ and reopen if issue persists after that.

**Comment by AmigaAbattoir** [comment]
Tried it out and still doesn't work as I expected:

Steps to reproduce:
1. Set in Preferences **General** > **Appearance** > **Theme:** to "Dark":
![Screen Shot 2021-11-22 at 2 08 20 PM](https://user-images.githubusercontent.com/6256023/142920788-7d298cac-248b-4d62-ae53-34b8bd2f1aa6.png)

2. Set **General** > **Appearance** > **Text Editors** to have a color palette like this:
![Screen Shot 2021-11-22 at 2 10 09 PM](https://user-images.githubusercontent.com/6256023/142920958-64b96b02-cdc4-4987-980d-bd264a5bdf80.png)
Most important:
_Background color_: #E6E6E6
_Foreground color_: #141618

3. Open a Javascript file (notice parenthesis, brackets, commas, semi-colons are not #141618 as in preferences) with **Switch to Theme...** > _Dark_
![Screen Shot 2021-11-22 at 2 16 51 PM](https://user-images.githubusercontent.com/6256023/142921795-63188727-eed2-4bf7-8b64-ccd7a059aa7e.png)

4. Change theme from one to another (was "Dark" to "Eclipse light"), (notice parenthesis, brackets, commas, semi-colons are #141618)
![Screen Shot 2021-11-22 at 2 14 54 PM](https://user-images.githubusercontent.com/6256023/142921849-4f40aaf2-dda5-4dc1-bff8-f532aee40279.png)

5. Lose focus of Eclipse (click on another programs window's or on you desktop), save the file, or switch tabs in Eclipse and the text that is expected to be #141618 is now light grey again:
![Screen Shot 2021-11-22 at 2 15 10 PM](https://user-images.githubusercontent.com/6256023/142922014-20342757-9d02-4801-b2dc-8e8662d8ccd6.png)

Expected results:
When changing theme, it stays the same after losing focus, saving or switching to other tabs.

**Comment by AmigaAbattoir** [comment]
I tried creating my own theme by taking the [Eclipse Light](https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui/themes/Eclipse-light.css) theme css, and added the following at the end:

```css
.editor { background-color: rgba(229, 229, 229, 1); color: rgb(20, 22, 24, 1); }
.editor.lineHighlight  {background-color:  rgba(232, 242, 254, 1); }
.editor.selection {}
```
This made no change.

Then started changing the background and foreground colors to dark. And noticed that when I changed the foreground color to yellow:

![Screen Shot 2021-11-23 at 12 43 03 PM](https://user-images.githubusercontent.com/6256023/143076935-30bb06b8-fa93-4b89-8bb3-f93cee713d63.png)

and I switched the theme from Dark to Eclipse Light and it honors the yellow color:

![Screen Shot 2021-11-23 at 12 43 29 PM](https://user-images.githubusercontent.com/6256023/143077044-e0afe92e-254d-4eec-bf6b-c439931ba65b.png)

Then, when the editor loses focus again (click on desktop, other window, change tabs) it becomes a grey again:

![Screen Shot 2021-11-23 at 12 43 46 PM](https://user-images.githubusercontent.com/6256023/143077145-e23d836c-e5ae-46f6-87a5-19f3c93cb947.png)

**Comment by mickaelistria** [comment]
When switching theme
1 call is with the Color from the Eclipse preferences
```Thread [main] (Suspended (breakpoint at line 9279 in StyledText))	
	StyledText.setForeground(Color) line: 9279	
	Theme.initializeViewerColors(StyledText) line: 167	
	TMPresentationReconciler.applyThemeEditorIfNeeded() line: 788	
	TMPresentationReconciler.applyThemeEditor() line: 777	
	TMPresentationReconciler.setTheme(ITokenProvider) line: 438	
	TMPresentationReconciler$ThemeChangeListener.preferenceThemeChange(String, IThemeManager) line: 171	
	TMPresentationReconciler$ThemeChangeListener.preferenceChange(IEclipsePreferences$PreferenceChangeEvent) line: 156	
	EclipsePreferences$2.run() line: 849	
	SafeRunner.run(ISafeRunnable) line: 45	
	InstancePreferences(EclipsePreferences).firePreferenceEvent(String, Object, Object) line: 852	
	InstancePreferences(EclipsePreferences).put(String, String) line: 864	
	ThemeManager.save() line: 137	
	ThemeContribution$1.run() line: 85	
	ThemeContribution$1(Action).runWithEvent(Event) line: 474	
...
```

then, with grey=170
```
Thread [main] (Suspended (breakpoint at line 9279 in StyledText))	
	StyledText.setForeground(Color) line: 9279	
	CSSSWTColorHelper.setForeground(Control, Color) line: 366	
	CSSPropertyTextSWTHandler.applyCSSPropertyColor(Object, CSSValue, String, CSSEngine) line: 75	
	CSSPropertyTextSWTHandler(AbstractCSSPropertyTextHandler).applyCSSProperty(Object, String, CSSValue, String, CSSEngine) line: 34	
	CSSPropertyTextSWTHandler.applyCSSProperty(Object, String, CSSValue, String, CSSEngine) line: 41	
	CSSSWTEngineImpl(AbstractCSSEngine).applyCSSProperty(Object, String, CSSValue, String) line: 746	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyleDeclaration(Object, CSSStyleDeclaration, String) line: 552	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyles(Object, boolean, boolean) line: 426	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyles(Object, boolean) line: 374	
	0x0000000100433568.accept(Object, Object) line: not available	
	AbstractCSSEngine.lambda$0(BiConsumer, boolean, Node) line: 258	
	0x00000001004337a0.accept(Object) line: not available	
	ForEachOps$ForEachOp$OfRef<T>.accept(T) line: 183	
	ReferencePipeline$3$1.accept(P_OUT) line: 197	
	Spliterators$ArraySpliterator<T>.forEachRemaining(Consumer<? super T>) line: 948	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).copyInto(Sink<P_IN>, Spliterator<P_IN>) line: 484	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).wrapAndCopyInto(S, Spliterator<P_IN>) line: 474	
	ForEachOps$ForEachOp$OfRef<T>(ForEachOps$ForEachOp<T>).evaluateSequential(PipelineHelper<T>, Spliterator<S>) line: 150	
	ForEachOps$ForEachOp$OfRef<T>.evaluateSequential(PipelineHelper, Spliterator) line: 173	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).evaluate(TerminalOp<E_OUT,R>) line: 234	
	ReferencePipeline$3(ReferencePipeline<P_IN,P_OUT>).forEach(Consumer<? super P_OUT>) line: 596	
	CSSSWTEngineImpl(AbstractCSSEngine).processNodeList(NodeList, BiConsumer<Node,Boolean>, boolean) line: 257	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyles(Object, boolean, boolean) line: 443	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyles(Object, boolean) line: 374	
	0x0000000100433568.accept(Object, Object) line: not available	
	AbstractCSSEngine.lambda$0(BiConsumer, boolean, Node) line: 258	
	0x00000001004337a0.accept(Object) line: not available	
	ForEachOps$ForEachOp$OfRef<T>.accept(T) line: 183	
	ReferencePipeline$3$1.accept(P_OUT) line: 197	
	Spliterators$ArraySpliterator<T>.forEachRemaining(Consumer<? super T>) line: 948	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).copyInto(Sink<P_IN>, Spliterator<P_IN>) line: 484	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).wrapAndCopyInto(S, Spliterator<P_IN>) line: 474	
	ForEachOps$ForEachOp$OfRef<T>(ForEachOps$ForEachOp<T>).evaluateSequential(PipelineHelper<T>, Spliterator<S>) line: 150	
	ForEachOps$ForEachOp$OfRef<T>.evaluateSequential(PipelineHelper, Spliterator) line: 173	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).evaluate(TerminalOp<E_OUT,R>) line: 234	
	ReferencePipeline$3(ReferencePipeline<P_IN,P_OUT>).forEach(Consumer<? super P_OUT>) line: 596	
	CSSSWTEngineImpl(AbstractCSSEngine).processNodeList(NodeList, BiConsumer<Node,Boolean>, boolean) line: 257	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyles(Object, boolean, boolean) line: 443	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyles(Object, boolean) line: 374	
	0x0000000100433568.accept(Object, Object) line: not available	
	AbstractCSSEngine.lambda$0(BiConsumer, boolean, Node) line: 258	
	0x00000001004337a0.accept(Object) line: not available	
	ForEachOps$ForEachOp$OfRef<T>.accept(T) line: 183	
	ReferencePipeline$3$1.accept(P_OUT) line: 197	
	Spliterators$ArraySpliterator<T>.forEachRemaining(Consumer<? super T>) line: 948	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).copyInto(Sink<P_IN>, Spliterator<P_IN>) line: 484	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).wrapAndCopyInto(S, Spliterator<P_IN>) line: 474	
	ForEachOps$ForEachOp$OfRef<T>(ForEachOps$ForEachOp<T>).evaluateSequential(PipelineHelper<T>, Spliterator<S>) line: 150	
	ForEachOps$ForEachOp$OfRef<T>.evaluateSequential(PipelineHelper, Spliterator) line: 173	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).evaluate(TerminalOp<E_OUT,R>) line: 234	
	ReferencePipeline$3(ReferencePipeline<P_IN,P_OUT>).forEach(Consumer<? super P_OUT>) line: 596	
	CSSSWTEngineImpl(AbstractCSSEngine).processNodeList(NodeList, BiConsumer<Node,Boolean>, boolean) line: 257	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyles(Object, boolean, boolean) line: 443	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyles(Object, boolean) line: 374	
	0x0000000100433568.accept(Object, Object) line: not available	
	AbstractCSSEngine.lambda$0(BiConsumer, boolean, Node) line: 258	
	0x00000001004337a0.accept(Object) line: not available	
	ForEachOps$ForEachOp$OfRef<T>.accept(T) line: 183	
	ReferencePipeline$3$1.accept(P_OUT) line: 197	
	Spliterators$ArraySpliterator<T>.forEachRemaining(Consumer<? super T>) line: 948	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).copyInto(Sink<P_IN>, Spliterator<P_IN>) line: 484	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).wrapAndCopyInto(S, Spliterator<P_IN>) line: 474	
	ForEachOps$ForEachOp$OfRef<T>(ForEachOps$ForEachOp<T>).evaluateSequential(PipelineHelper<T>, Spliterator<S>) line: 150	
	ForEachOps$ForEachOp$OfRef<T>.evaluateSequential(PipelineHelper, Spliterator) line: 173	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).evaluate(TerminalOp<E_OUT,R>) line: 234	
	ReferencePipeline$3(ReferencePipeline<P_IN,P_OUT>).forEach(Consumer<? super P_OUT>) line: 596	
	CSSSWTEngineImpl(AbstractCSSEngine).processNodeList(NodeList, BiConsumer<Node,Boolean>, boolean) line: 257	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyles(Object, boolean, boolean) line: 443	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyles(Object, boolean) line: 374	
	0x0000000100433568.accept(Object, Object) line: not available	
	AbstractCSSEngine.lambda$0(BiConsumer, boolean, Node) line: 258	
	0x00000001004337a0.accept(Object) line: not available	
	ForEachOps$ForEachOp$OfRef<T>.accept(T) line: 183	
	ReferencePipeline$3$1.accept(P_OUT) line: 197	
	Spliterators$ArraySpliterator<T>.forEachRemaining(Consumer<? super T>) line: 948	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).copyInto(Sink<P_IN>, Spliterator<P_IN>) line: 484	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).wrapAndCopyInto(S, Spliterator<P_IN>) line: 474	
	ForEachOps$ForEachOp$OfRef<T>(ForEachOps$ForEachOp<T>).evaluateSequential(PipelineHelper<T>, Spliterator<S>) line: 150	
	ForEachOps$ForEachOp$OfRef<T>.evaluateSequential(PipelineHelper, Spliterator) line: 173	
	ReferencePipeline$3(AbstractPipeline<E_IN,E_OUT,S>).evaluate(TerminalOp<E_OUT,R>) line: 234	
	ReferencePipeline$3(ReferencePipeline<P_IN,P_OUT>).forEach(Consumer<? super P_OUT>) line: 596	
	CSSSWTEngineImpl(AbstractCSSEngine).processNodeList(NodeList, BiConsumer<Node,Boolean>, boolean) line: 257	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyles(Object, boolean, boolean) line: 443	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyles(Object, boolean) line: 374	
	0x0000000100433568.accept(Object, Object) line: not available	
	CSSSWTEngineImpl(AbstractCSSEngine).processNodeList(NodeList, BiConsumer<Node,Boolean>, boolean) line: 263	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyles(Object, boolean, boolean) line: 443	
	CSSSWTEngineImpl(AbstractCSSEngine).applyStyles(Object, boolean) line: 374	
	ThemeEngine.applyStyles(Object, boolean) line: 553	
	PartRenderingEngine$7.setClassnameAndId(Object, String, String) line: 1319	
	WBWRenderer(SWTPartRenderer).setCSSInfo(MUIElement, Object) line: 114	
	WBWRenderer.updateNonFocusState(int, MWindow) line: 616	
...
```

**Comment by mickaelistria** [comment]
This issue is in Eclipse Platform theme engine https://bugs.eclipse.org/bugs/show_bug.cgi?id=577472 .
Let's close it here and move to https://bugs.eclipse.org/bugs/show_bug.cgi?id=577472
