### ISSUE TITLE
Cannot import language-configuration.json file

### ISSUE THREAD

**Issue by bostick** [eclipse/tm4e#258]
When adding a new Language Configuration, I cannot select the language-configuration.json file in the dialog.

In the Language Configuration preferences, I click on New

I then click on Browser FileSystem...

I navigate to the file that I want to import, but I cannot select it.

See the screenshot.

<img width="936" alt="Screen Shot 2020-10-07 at 8 56 02 AM" src="https://user-images.githubusercontent.com/183619/95340834-436abb80-087b-11eb-8331-9f357d73ad79.png">

Am I missing something?

I have the latest versions of the plugins as of Oct 7 2020

**Comment by mickaelistria** [comment]
As the dialog suggests, the file has to be named `<whatever>language-configuration.json`. Does your file match this pattern?

**Comment by bostick** [comment]
Yes. I meant to say originally... you can see the wolfram.language-configuration.json file in the screenshot of the dialog and it is not selectable.

I also tried having a file just named language-configuration.json and it was not selectable, either

**Comment by mickaelistria** [comment]
On Linux, I can select files named "language-configuration.json". It looks like a limitation on macOS FileDialog.

**Comment by bostick** [comment]
Do we know whether the fix is to dig into the guts of the dialog, or to simply remove the filter?

**Comment by mickaelistria** [comment]
> Do we know whether the fix is to dig into the guts of the dialog, or to simply remove the filter?

I don't know and I think the contract of FileDialog (in SWT) needs to be checked. Maybe SWT placed a wrong contract regarding `*` handling, or macOS changed its contract and f*** up SWT (that wouldn't be the first time...). Or maybe TM4E is doing something wrong...
I'm personally a bit tired of macOS specific issues which and won't invest time on this topic soon (or ever). Please keep investigating and feel free to use this ticket to track your progress.

**Comment by bostick** [comment]
If this is not ever going to get developer time invested in it, then at least could the filter be removed?

It is frustrating to not be able to use this on Mac.

**Comment by mickaelistria** [comment]
Someone who have a mac would need to spend time looking at it. I'm not aware of any regular contributor to TM4E using a mac. If you're interested in trying it, I'll gladly assist you in getting started contributing.

**Comment by PyvesB** [comment]
Out of interest, what version of macOS are you using? There are problems with these kind of embedded Finder dialogues in macOS 11 betas, I believe there's an Eclipse bug for it somewhere. An earlier version of macOS should be fine though, investigation in tm4e would be required in that case :)

**Comment by bostick** [comment]
I am on MacOS 10.15.7

**Comment by sebthom** [comment]
@bostick Does this issue still exist when tried in newer Eclipse versions?

**Comment by sebthom** [comment]
Closing issue for now. If problem still exists, please re-open.
