### ISSUE TITLE
any reason why we don't follow the more known keybinding eclipse uses for toggle line comments?

### ISSUE THREAD

**Issue by jcompagner** [eclipse/tm4e#269]
https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.languageconfiguration/plugin.xml#L91

why is chosen for the default CTRL-SHIFT-C and not what eclipse (java, js editors) standard use: CTRL-/  ?

**Comment by mickaelistria** [comment]
Ctrl+/ is not standard, it's used widely for languages that have `/` based comments, but many languages do not use this pattern for comments. Ctrl+Shift+C is more generic as the C stands for comment.
Enabling other more specific shortcuts for comment is something that should be implemented in downstream consumers according to language specificities, not something that TM4E should provide.

**Comment by ZeeD** [comment]
@mickaelistria please reconsider this choice.
first of all, IMHO your reasons miss the fact that the users of tm4e are actually eclipse users, so the "standard" is the one of the platform (CTRL-/)
moreover keep in mind that I am facing a lot of troubles trying to change the settings in the keybinding preferences, as it seems there are conflicts or something and - as a matter of fact - I cannot reliably change them.

BTW: in my experience Ctrl+Shift+C means *copy* (it's used in Konsole and other terminal emulators to distinguish it from "Ctrl+C" that terminates processes
