### ISSUE TITLE
Very long lines make the IDE freeze

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#274]
See https://github.com/eclipse/wildwebdeveloper/issues/656

**Comment by jensli** [comment]
I think this is common to all editors based on `org.eclipse.ui.editors.text.TextEditor`.

I have seen it in the normal Eclipse text editor when trying to edit really long lines.

**Comment by mickaelistria** [comment]
Thanks! Is there a bug already existing for this issue in Eclipse Platform tracker? If not, can you please create one? And then add link to the Platform issue here?

**Comment by jensli** [comment]
There are various Bugzilla tickets about performance problems with `StyledText`.

About word-wrap:

**Comment by jensli** [comment]
There are various Bugzilla tickets about the performance of SWT's `StyledText` with long lines. I don't know if any of them describe your exact problem. Here are a couple.

About long lines with word-wrap:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=168557

Thomas Schindl about long lines in general:

> StyledText is optimized for not too long lines.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=499039
