### ISSUE TITLE
unicode bug

### ISSUE THREAD

**Issue by Lzhiyong** [eclipse/tm4e#278]
Support for unicode does not seem to be very good, I don’t know how to fix it.

OS: Android 10
Theme: OneLight.json
Grammar: java.tmLanguage.json

![Screenshot_2021-08-09-15-43-19-766_com text edit](https://user-images.githubusercontent.com/36750502/128674430-4cbb2a91-b573-448d-a4a0-af4ce2544bfe.jpg)

**Comment by mickaelistria** [comment]
How is this related to the Eclipse TM4E project?

**Comment by Lzhiyong** [comment]
> How is this related to the Eclipse TM4E project?

Sorry, but the core is universal, whether it is Eclipse or Android, I just want to say that unicode still has problems!

**Comment by mickaelistria** [comment]
Are you using Eclipse TM4E, yes or no?
TM4E is not responsible for Unicode or text rendering, hence why I think your issue is not related.

**Comment by Lzhiyong** [comment]
> Are you using Eclipse TM4E, yes or no?
> TM4E is not responsible for Unicode or text rendering, hence why I think your issue is not related.

Yes, I ported core to Android, except for unicode a little problem, everything else is fine.

**Comment by mickaelistria** [comment]
OK, so

**Comment by mickaelistria** [comment]
OK, so please consider reprortimg programatic steps to reproduce, such as a unit test.
I still believe that TM4E is not related to Unicode character rendering since it only *reads* the file, but I'd be glad to be proven wrong.

**Comment by Lzhiyong** [comment]
I have solved it, due to the use of the wrong API method caused some problems, from `vscode-textmate/src/tests/themedTokenizer.ts`
