### ISSUE TITLE
Drop org.eclipse.tm4e.markdown ?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#286]
It seems like no project is using org.eclipse.tm4e.markdown. Moreover, a more important project exists in the Java ecosystem to render Markdown to HTML (commonmark), and mylyn-docs in the Eclipse ecosystem is also capable of some rendering. Some other technologies such as highlight-js are also successfully used in order to style the nested code in markdown files.
Shouldn't we simply drop this part of TM4E (which is not really related to TextMate anyway) ?

**Comment by sebthom** [comment]
What is the conclusion here? Shall we drop or keep the markdown plugin?

**Comment by mickaelistria** [comment]
IMO, drop.

**Comment by angelozerr** [comment]
Are you sure that you can have https://github.com/eclipse/tm4e/issues/286#issuecomment-944226647 with Mylyn ?

The markdown tm4e uses the tm4E textmate support to highlight code.

**Comment by mickaelistria** [comment]
The reason to drop is not what it does or does not do, it's that since no-one is using it, no-one is maintaining it, and people who have similar need have preferred other alternatives.

**Comment by angelozerr** [comment]
> The reason to drop is not what it does or does not do, it's that since no-one is using it, no-one is maintaining it, and people who have similar need have preferred other alternatives.

I understand totally what you mean, but I think before dropping this plugin, it should be really nice to compare with MyLyn.

Here the advantage of this markdown plugin:

 * should have the same renderer than vscode (because I translated the markdown library written in JS used in vscode into Java)
 * very well integrated with tm4e when code should be renderer. In otherwise the markdown renderer code is the same color than editor.

**Comment by mickaelistria** [comment]
@angelozerr we already know all that, and yet we're happy to stick with Mylyn at the moment.

**Comment by angelozerr** [comment]
@mickaelistria do you think LSP4E could provide an extension point to provide markdown support?

In this case we could provide a MyLyn and TP4E markdown support, what do you think about that?

**Comment by mickaelistria** [comment]
I don't know for others, but out te has no an at all to add such extension point nor to use tm4e.markdown.
But let's keep it if it makes you happier.
