### ISSUE TITLE
Change background color when editor is read only?

### ISSUE THREAD

**Issue by rubenporras** [eclipse/tm4e#290]
Hi,

I am migrating from a coustom Eclipse Editor to an ExtensionBasedTextEditor, and will use TM4e to color the document. One feature that I must keep is that if the document is read only, the background of the editor must have a different color (e.g. grey instead of white).

I am right to think that I should use TM4E to apply a theme to the document. I have seen the method org.eclipse.tm4e.ui.text.TMPresentationReconciler.applyThemeEditor(), and that would be clone to what I need. What I do not know is how to make TM4E apply different themes depending on a property, such as editability of the document.

Is it possible to achieve that?

Kind Regards

**Comment by mickaelistria** [comment]
I don't think TM4E is the right layer to change the background color of the editor according to the "read-only" mode.
You can maybe try to use an IPartListener to invoke `((StyledText)textEditor().getAdapter(Control.class)).setBackgroundColor(display.getSystemColor(SWT.COLOR_TEXT_DISABLED_BACKGROUND))` when the editor is the one you want to customize.

**Comment by rubenporras** [comment]
Thanks, 

I could try that, how could I add one of this listeners?

So far I have only created a custom DocumentProvider to customize the behaviour of the editor, but I do not see how to get the text editor from this document provider or  from the created document.

Do you know how one can get the editor from the document provider or the document itself?

**Comment by mickaelistria** [comment]
> how could I add one of this listeners?

This needs to be done at workbench level, for example when activating your bundle, or -if it's not always active in case such editor is open- using the `org.eclipse.ui.startup` extension point.

**Comment by rubenporras** [comment]
Thanks,

I have created this class which seems to work fine

public class ReadOnlyViewerBackgroundSetterPartListener implements IPartListener2 {

  /** Class-wide logger. */
  private static final Logger LOGGER = Logger.getLogger(ReadOnlyViewerBackgroundSetterPartListener.class);

  private void greyOutReadOnlyViewer(final IWorkbenchPart part) {
    if (part instanceof ITextEditor) {
      ITextEditor editor = ((ITextEditor) part);
      IEditorInput editorInput = editor.getEditorInput();
      boolean readOnly = false;
      if (editorInput instanceof IFileEditorInput) {
        try {
          readOnly = ((IFileEditorInput) editorInput).getStorage().isReadOnly();
        } catch (CoreException e) {
          LOGGER.error("Error when getting read only property from the storage"); //$NON-NLS-1$
        }
      }
      if (!readOnly) {
        ITextViewer sourceViewer = editor.getAdapter(ITextViewer.class);
        if (sourceViewer != null) {
          readOnly = !sourceViewer.isEditable();
        }
      }
      if (!readOnly) {
        editor.getAdapter(Control.class).setBackground(Display.getCurrent().getSystemColor(SWT.COLOR_TEXT_DISABLED_BACKGROUND));
      }
    }
  }

  @Override
  public void partActivated(final IWorkbenchPartReference partReference) {
    greyOutReadOnlyViewer(partReference.getPart(false));
  }

  @Override
  public void partOpened(final IWorkbenchPartReference partReference) {
    greyOutReadOnlyViewer(partReference.getPart(false));
  }

  /**
   * The Class Initializer for early startup.
   */
  public static class Initializer implements IStartup {

    @Override
    public void earlyStartup() {
      final IWorkbench workbench = PlatformUI.getWorkbench();
      workbench.getDisplay().asyncExec(() -> {
        IWorkbenchWindow window = workbench.getActiveWorkbenchWindow();
        if (window != null && window.getActivePage() != null) {
          window.getActivePage().addPartListener(new ReadOnlyViewerBackgroundSetterPartListener());
        } else {
          LOGGER.error("Early startup for concurrent edit support failed"); //$NON-NLS-1$
        }
      });
    }
  }

}

Is this what you expected?

Thank you

**Comment by mickaelistria** [comment]
Yes, this is what I had in mind. I think it better resolves your use-case as it doesn't require you to tweak any existing code, and it also separate your own application logic (regarding how to render read-only editors) into a dedicated piece of work that can be used for more editors.

**Comment by rubenporras** [comment]
Thank you
