### ISSUE TITLE
Feature request: Continue existing style when typing in region of styled text

### ISSUE THREAD

**Issue by ainsley** [eclipse/tm4e#30]
When I type in a syntax highlighted region of a document, as I type, the text I type is always white, even if the region I am typing in (for example) is yellow. I can see that the syntax highlighting only executes when I stop typing for a few milliseconds, then the text I just typed becomes yellow as it should (in this particular example).

![text should be yellow](https://cloud.githubusercontent.com/assets/201870/21706985/09002f5c-d3c3-11e6-8dc6-693b8065b680.gif)

I think the better behaviour is to either adopt the style of the character to the left when typing, then do the full recalculate with corrections on the existing time OR even better, to calculate the style of the first character only in context, then use that for all the typed characters before fully re-rendering. 

The second approach is better than the first in my opinion in the case of quoted text. In quoted text, the quotes might be of the punctuation style, and the text will be in the literal text style. If we take the first approach and adopt the character to the left (or the style of the last character on the previous line, then as the user types, it will be in the style of the punctuation. Taking the second approach it will be in the style of the quoted text. 

The ideal approach is obviously to calculate the style per character instantly but I don't know if that is possible within the constraints of the implementation so calculating the first character then carrying that forward until a full revalidation of the dirty region is performed seems like a reasonable workaround.

**Comment by angelozerr** [comment]
@ainsley please update TM4e and tell me if it improve your case. I have just set the delay to 1 (instead of setting to 200). It works for me (typescript.java) even with big file, please tell me if it's OK for you.

**Comment by ainsley** [comment]
@angelozerr I just tried it out and the delay is indeed reduced, good work.

That said, there is still a "flicker" when entering text. This is especially prevalent when entering a block of text, such as from a copy and paste. It's not a major issue, but it still remains.

**Comment by angelozerr** [comment]
> That said, there is still a "flicker" when entering text. This is especially prevalent when entering a block of text, such as from a copy and paste. 

Could you attach an vide demo with your problem?

**Comment by mickaelistria** [comment]
@ainsley I think that would be relatively easy to fix this on the Eclipse side, it's just a matter of propagating the style to the new characters, and let it be overriden later asynchronously by TextMate tokens. Is the user-story that drove you to this request in the Eclipse IDE or some other editor?

**Comment by mickaelistria** [comment]
Done with #74
