### ISSUE TITLE
Wrong equals object?

### ISSUE THREAD

**Issue by danipen** [eclipse/tm4e#311]
Is this condition correct? https://github.com/eclipse/tm4e/blob/1ee8f06318cfed42c73fd4c2d21907acc1fee575/org.eclipse.tm4e.core/src/main/java/org/eclipse/tm4e/core/grammar/StackElement.java#L91

Note that the condition is negated:
`!Objects.equals(a.endRule, b.endRule)`

**Comment by mickaelistria** [comment]
It indeed seems wrong. Please submit a PR to fix that.
