### ISSUE TITLE
Syntax colouring lost after file compare

### ISSUE THREAD

**Issue by sgjohnston** [eclipse/tm4e#321]
If I have a JavaScript file open in the text editor, and I then compare the file (eg with the head revision), either from the package explorer or the git staging view, and then go back to the file in the editor, as soon as an edit in the file is made the syntax colouring in the file will be lost. The syntax colouring will gradually disappear as the file is edited, and the only way to resolve is to close the editor and reopen. No change needs to be made in the compare editor for this to happen, just opening the compare seems to be enough. There are possible also some other related artefacts, such as syntax errors being incorrectly highlighted. 

There are no obvious issues in the language server logs. 

Eclipse IDE for Java Developers	4.22.0.20211202-1200	epp.package.java	Eclipse Packaging Project (on a Mac)
Wild Web Developer HTML, CSS, JSON, Yaml, JavaScript, TypeScript, Node tools	0.10.10.202111090852	org.eclipse.wildwebdeveloper.feature.feature.group	Eclipse Wild Web Developer project

**Comment by mickaelistria** [comment]
This seems fixed now in latest snapshot, thanks to #341 by @vrubezhny
