### ISSUE TITLE
StringIndexOutOfBoundsException in org.eclipse.tm4e.ui when opening .js file

### ISSUE THREAD

**Issue by Omcsesz** [eclipse/tm4e#326]
Hello, Team!

When opening the following file: https://github.com/freegroup/draw2d/blob/master/examples/draw2d.js ,
I get the following error on the Error log:
![TM4EErrorLog.log](https://github.com/eclipse/tm4e/files/8442984/TM4EErrorLog.log)
I'm using the latest version of Eclipse, and Win10.

Can you please support?

**Comment by mickaelistria** [comment]
Can you please try latest snapshots? #340 may have fixed it.

**Comment by mickaelistria** [comment]
Please close issue after testing if issue if fixed.

**Comment by sebthom** [comment]
Works fine for me with the latest builds. Closing the issue for now, please reopen if the problem still occurs.

![image](https://user-images.githubusercontent.com/426959/171463281-c2088549-19aa-4295-879e-7409a5ab30f5.png)
