### ISSUE TITLE
Tests for TMPresentationReconciler

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#33]
*  do tests for for TMPresentationReconciler
 * implement a test generator to generate tests when editor consumes TextMate grammar.

**Comment by mickaelistria** [comment]
@angelozerr is there already an integration test that simply opens an editor and check that highlighting is performed?

**Comment by angelozerr** [comment]
@mickaelistria the only test that I have done is https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui.tests/src/test/java/org/eclipse/textmate4e/ui/text/typescript/TMPresentationReconcilerTypeScriptTest.java

I have tried to emulate an editor. It works well with Windows OS but not for Linux. Because of `org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]`

To see this problem remove https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui.tests/src/test/java/org/eclipse/textmate4e/ui/text/typescript/TMPresentationReconcilerTypeScriptTest.java#L17

If you think it's a bad idea, please change it. I have not a big experience to test that

**Comment by angelozerr** [comment]
@mickaelistria I have forgotten to say you that you can activate test generator https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/text/TMPresentationReconciler.java#L70

I will generate you test with `TMPresentationReconcilerTestGenerator` when you will open an editor and when you will change the content of the editor. It misses the assert part but it tracks the whole event of the editor (when editor is opened, changed, when text presentation is invalidated with annotations, closed)

**Comment by mickaelistria** [comment]
Ok. I'd like to create a test associating some grammar with some content-type and opening it in the generic editor. Is it ok with you?

**Comment by angelozerr** [comment]
Yes sure! But it means that we will have dependencies with Generic Editor. Please set this dependencies just for tests.

**Comment by mickaelistria** [comment]
Ok, I'll add the generic editor to the TP, and put an optional dependency on it for tests and use a Assert.assumeThat(...) to skip related tests if generic editor is missing.

**Comment by angelozerr** [comment]
Great! Thanks.

**Comment by sebthom** [comment]
Closing the issue as TMinGenericEditorTest and TMPresentationReconcilerTypeScript are testing the TMPresentationReconciler
