### ISSUE TITLE
Use LinkedList in place of MoreCollections

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#388]
The code introduces a MoreCollections util class to manipulate some List. However, this wouldn't be necessary of relying on the proper type of collection in 1st place. In most places where MoreCollections is used, a LinkedList would give better results.

**Comment by sebthom** [comment]
I actually have doubts about this. First LinkedList have a significant memory overhead over ArrayLists. Also I seem to remember having seen benchmarks where they showed that LinkedLists are basically only beneficial when adding/removing elements in the middle of a list (which would result in expensive array copy operations in ArrayList).

Anyways, I am currently working on a benchmark module based on JMH we can use to establish performance baselines and then compare changes like switching LinkedLists for ArrayLists or even using specialized primitive lists to see if certain changes are worth it or have the opposite effect.

**Comment by mickaelistria** [comment]
OK, and what about using Deque/ArrayDeque instead?

**Comment by sebthom** [comment]
With PR #392 I replaced ArrayList+MoreCollections where was possible. Unfortunately ArrayDeque does not implement the List interface which means it misses the random access capability so I could not use it everywhere as a replacement.
