### ISSUE TITLE
TODO/FIXME comment markers

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#405]
TM4E could read the ranges that are parsed as "comments" and find the TODO and FIXME in them to annotate them as Tasks.
See https://www.eclipse.org/lists/tm4e-dev/msg00071.html

**Comment by sebthom** [comment]
@mickaelistria can you point me to some example code how to place todo markers?

**Comment by mickaelistria** [comment]
I think it's "only" a matter of invoking `resource.createMarker(IMarker.TASK, attributes)`, where attributes configure the usual value for IMarker.CHAR_START, IMarker.LINE_NUMBER...

**Comment by sebthom** [comment]
@mickaelistria  any idea how to get the corresponding IResoure for an IDocument?

**Comment by akurtakov** [comment]
Have you tried document.getAdapter(IResource.class) ?

**Comment by sebthom** [comment]
ah, no. will give it a try, thanks!

**Comment by mickaelistria** [comment]
> Have you tried document.getAdapter(IResource.class) ?

`Adapters.adapt(document, IResource.class)` would be better. I never tried it, if it works, it's really great! We have tons of hacks in LSP4E for that and actually having adapter factories in Platform is the best solution.
If it's not working yet, I'd like to try fixing it in a near-ish future.

>  any idea how to get the corresponding IResoure for an IDocument?

In LSP4E, we use something like
```java 
ITextFileBuffer buffer = ITextFileBufferManager.DEFAULT.getTextFileBuffer(document);
if (buffer == null || buffer.getLocation() != null) {
  return null;
}
if (new File(buffer.getLocation()).isAbsolute()) {
  return null;
}
return workspace.getRoot().findMember(buffer.getLocation());
```
but if what @akurtakov suggests works, then let's use it, it's by far better.

**Comment by sebthom** [comment]
My observations:

- `IDocument` has no `getAdapter` method.
- `Adapters.adapt(document, IResource.class);` returns `null`.
- This seems to work:
   ```java
   IResource getResource(IDocument doc) {
     var buffer = ITextFileBufferManager.DEFAULT.getTextFileBuffer(doc);
     if (buffer == null || buffer.getLocation() == null)
        return null;
     return ResourcesPlugin.getWorkspace().getRoot().findMember(buffer.getLocation());
   }
   ```
   However the `getTextFileBuffer` javadoc says: **This method goes through the list of registered buffers and tests whether its document matches the given one. Therefore this method should not be used in performance critical code.** So I am not sure if this will have an impact on UI responsiveness.

**Comment by mickaelistria** [comment]
> So I am not sure if this will have an impact on UI responsiveness.

Resolving IDocument to IResource should only happen once per TODO/FIXME, so it's not much. It can/should also happen out of the UI Thread (in a Job, or a Future). So overall, I don't think this will cause a noticeable penalty. Maybe it will take ~200ms to get them in the Tasks view, but it would be very acceptable. Even a few seconds would be OK for that use-case, as long as UI is not frozen.

**Comment by nitind** [comment]
Isn't this a flawed premise? Detecting tasks only once a file is opened in an editor is unlike other language support in Eclipse, and too late to be useful to the user.

**Comment by sebthom** [comment]
@mickaelistria do you feel the current implementation is sufficient to close this issue?

**Comment by mickaelistria** [comment]
Yes, thanks!
