### ISSUE TITLE
Problem with Importing *.css TextMate theme

### ISSUE THREAD

**Issue by SLH-Bin** [eclipse/tm4e#409]
Hi,
I edited a little bit the *.css theme (Monokai) downloaded from [here ](https://github.com/eclipse/tm4e/tree/master/org.eclipse.tm4e.ui/themes) and tried to add it as a TextMate theme. When I add it, all text is white:

![image](https://user-images.githubusercontent.com/106489836/172047127-cbdf0fa3-9d9e-47e3-b5c4-039213ab2eb0.png)

What should I do to use this *.css file?

**Comment by mickaelistria** [comment]
I can reproduce the issue and confirm this is a bug.
