### ISSUE TITLE
Upgrading eclipse 2022-03 to 2022-06 not possible due to "No repository found containing: osgi.bundle,org.eclipse.tm4e.registry,0.5.2.202206141553"

### ISSUE THREAD

**Issue by MahatmaFatalError** [eclipse/tm4e#422]
Spring Tool Suite 4 
Version: 4.14.1.RELEASE
Build Id: 202204250734

```
An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.tm4e.registry,0.5.2.202206141553
No repository found containing: osgi.bundle,org.eclipse.tm4e.ui,0.5.2.202206151250
```

I do not know which bundle is requiring tm4e. Version 0.5.2.202206151250 looks strange to me when I look at https://github.com/eclipse/tm4e/releases

**Comment by mickaelistria** [comment]
This comes from https://download.eclipse.org/tm4e/snapshots/ which has mutable content. So your cached copy of the repo is most likely not in sync with remote one. You may try restarting the IDE and click "Reload" button in Window > Preferences > Install/Update > Available Software Sites.
I'm closing as this is not a TM4E issue but a recurring issue with p2 installer failing at refreshing its cache.
