### ISSUE TITLE
By default hpp files are not opened with CDT editor anymore if language pack is installed

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse/tm4e#437]
1. Get 4.25 SDK
2. Create simple project and empty hello.hpp file
3. Install CDT SDK into it, restart
4. Double click on hello.hpp - it is opened in default C++ editor from CDT. 
5. Right click in explorer -> "Open with" shows C++ editor in the proposed editors list
6. Close C++ editor.
7. Install org.eclipse.tm4e (TextMate support in Eclipse IDE, 0.5.1.202207061559) and  org.eclipse.tm4e.language_pack (TextMate Language Pack, 0.1.0.202206131926)
8. Restart Eclipse
9. Double click on hello.hpp - it is opened in generic text editor, NOT with CDT C++ editor.
10. Right click in explorer -> "Open with" does NOT show C++ editor in the proposed editors list

**Comment by iloveeclipse** [comment]
@howlger, @jonahgraham: FYI.

**Comment by mickaelistria** [comment]
> Double click on hello.hpp - it is opened in generic text editor, NOT with CDT C++ editor.

I wouldn't qualify that as a bug, it's just that there are 2 editors with apparently equal priority, so it's more or less like throwing a coin to decide which editor wins (although it may be a determistic coin).

> Right click in explorer -> "Open with" does NOT show C++ editor in the proposed editors list

I would qualify it as a bug in Platform as it doesn't meet user expectation here.

**Comment by iloveeclipse** [comment]
@mickaelistria : sure it is a bug, and it is deterministic. CDT priority is high, textmate is low. Textmate editor shouldn't ever be opened by default if CDT is installed.

**Comment by mickaelistria** [comment]
> it is deterministic. CDT priority is high, textmate is low

Based on which criteria that the Platform knows about?

**Comment by iloveeclipse** [comment]
Based on contribution priority attribute, see above.

**Comment by mickaelistria** [comment]
> Based on contribution priority attribute, see above.

OK, my bad, I missed it. So yes, this is a bug, in Platform most likely.

**Comment by mickaelistria** [comment]
I confirm this is Platform: https://github.com/eclipse-platform/eclipse.platform/blob/c198507304892befd104b82dc7af20a0dedb4494/runtime/bundles/org.eclipse.core.contenttype/src/org/eclipse/core/internal/content/ContentTypeCatalog.java#L47 . I believe the chosen heuristic is arguable and can be improved.
But report this issue to Platform as there is nothing Wild Web Developer can nor should do here.
