### ISSUE TITLE
"Toggle Block Comment" handler should fail back to "Toggle Lines comment" if there are no block comment

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#450]
"Toggle Block Comment" handler should fail back to "Toggle Lines comment" if there are no block comment.
The goal is to have Ctrl+Shift+/ working in XML editor (whose language-configuration doesn't define block comment).

**Comment by mickaelistria** [comment]
@vrubezhny Please have a look if you are available to do so soon (no need to shamble other pending tasks,this one can wait if necessary)

**Comment by sebthom** [comment]
@mickaelistria is this issue fully resolved by  #463 ?

**Comment by mickaelistria** [comment]
Should be.
