### ISSUE TITLE
Language configuration files for TypeScript and others cannot be found

### ISSUE THREAD

**Issue by AndrewFerr** [eclipse/tm4e#467]
Version: `0.5.0.202206241118`

When editing a TypeScript file, the Error Log repeatedly fires an error for not being able to find a language configuration file:
```
Plug-in: org.eclipse.tm4e.languageconfiguration
Severity: Error
Message: /language-configurations/typescript/language-configuration.json
Exception Stack Trace: java.io.FileNotFoundException: /language-configurations/typescript/language-configuration.json
```

Auto-indenting behaviour is also broken for TypeScript files.

It looks like this is because Wild Web Developer provides this file, but renamed it to `*.jsonc` in its latest release.  This renaming was also done to the language configuration files for JavaScript and HTML.  Maybe something in TM4E needs to be updated to recognize that change.

For now, a workaround is to manually create the `*.json` files that TM4E expects to see, by making them symlinks that point to the new `*.jsonc` files.  When I do that, TypeScript files regain their auto-indenting behaviour.

**Comment by mickaelistria** [comment]
Please try latest release, version 1.0.0

**Comment by AndrewFerr** [comment]
Thanks!  Do you mean 1.0.0 of Wild Web Developer?  My Eclipse isn't picking up that update, but it looks like it's rather new, so I can just wait for it to become available.

**Comment by AndrewFerr** [comment]
Actually, the version of `org.eclipse.wildwebdeveloper` that's installed is `1.0.0.202211030226`.  All other plugins are up-to-date, too.

**Comment by mickaelistria** [comment]
If the issue is only for TypeScript files with Wild Web Developer, then it should be reported to Wild Web Developer project.
But Wild Web Developer 1.0 does reference the *.jsonc file: https://github.com/eclipse/wildwebdeveloper/blob/1.0.0/org.eclipse.wildwebdeveloper/plugin.xml#L603 ; so I suspect an older or a corrupted version is still in use in your installation.

**Comment by AndrewFerr** [comment]
You're right, it was a configuration issue...but the culprit was not a bad installation, but a workspace config setting: `.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.tm4e.languageconfiguration.prefs` held references to the outdated language configuration filenames.  With that said, this issue may be closed.

...But how in the heck did that preference file get there??  I never touched that it myself or customized my workspace's language configurations (and I don't even know how to do that).  Maybe it was generated when upgrading Eclipse from the June release to the September release, as two separate upgraded installations both had that file & the same problem.  Upgrading WWD alone doesn't generate it, as I spun a fresh Eclipse with the previous version of WWD, updated it, and didn't get the error before & after the update.

Maybe it'd be worth checking how/if tm4e workspace configuration changes between updates, because if updates do break it, it's incredibly hard for users to figure out what happened.

**Comment by AndrewFerr** [comment]
Aha...what generated that file was having customized the "Auto Closing Pairs" behaviour of JavaScript & TypeScript files for my workspace.  It must be that the generated preferences file sticks around between WWD updates, and since it refers to the targeted filetype by the path to its language configuration file, the path it points to may become stale if the language configuration file name changes.
