### ISSUE TITLE
Drop reference to org.sonatype.oss:oss-parent

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#49]
As the infrastructure is moving to Eclipse.org, maybe there's an opportunity to drop the reference to org.sonatype.oss:oss-parent .
@pascalleclercq Which feature provided by the parent is tm4e using?

**Comment by pascalleclercq** [comment]
@mickaelistria you are perfectly right we have to drop the parent pom.xml I use org.sonatype.oss:oss-parent  for other projects and probably copy/pasted It.
Will do It ASAP.

**Comment by pascalleclercq** [comment]
There's more cleanup that can be done in the pom.xml like the ftp upload configuration. I think we can drop also the pushToBintray.sh.

**Comment by mickaelistria** [comment]
let's keep the pushToBintray.sh until we have builds published fully at Eclipse.org.
We'll add a pushToDownloadEclipseOrg.sh, make it work, and then we can consider dropping bintray.

**Comment by pascalleclercq** [comment]
Ok, sounds good

**Comment by angelozerr** [comment]
@pascalleclercq can we close this issue? It seems it was resolved with https://github.com/eclipse/tm4e/pull/52

**Comment by pascalleclercq** [comment]
Yes, indeed we can close It !
