### ISSUE TITLE
TM4E language_pack definitions taking priority over CDT ones in some cases

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/tm4e#499]
If you open a `.hpp` file in Eclipse with both CDT and TM4E installed it opens in the generic editor instead of the CEditor.

My reading of the TM4E code is that the intention was that the language_pack definitions were supposed to be lower [priority](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/reference/extension-points/org_eclipse_core_contenttype_contentTypes.html) that things the user already had installed.

However, it turns out that the way Eclipse chooses a content type depends on the ["depth"](https://github.com/eclipse-platform/eclipse.platform/blob/9839c18f52687db6f949bdb56a59a5d20cd7c938/runtime/bundles/org.eclipse.core.contenttype/src/org/eclipse/core/internal/content/ContentTypeCatalog.java#L43-L60) of the content type by considering how many base types it has. And CDT's content type for `.hpp` files is deeper than TM4E's one.

Therefore, in the absence of touching [ContentTypeCatalog](https://github.com/eclipse-platform/eclipse.platform/blob/9839c18f52687db6f949bdb56a59a5d20cd7c938/runtime/bundles/org.eclipse.core.contenttype/src/org/eclipse/core/internal/content/ContentTypeCatalog.java#L43-L60) code that hasn't been changed since 2005, I will provide a PR to resolve the issue by creating artificial depth.

**Comment by mickaelistria** [comment]
Seems like #437 by the way.

**Comment by jonahgraham** [comment]
With the fix for https://github.com/eclipse-platform/eclipse.platform/issues/151 merged this is now resolved in platform.
