### ISSUE TITLE
Fix bugs with synch between TextMate model and editor

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#5]
The colorization is done with async mode to avoid having freeze (like VSCode does): it means that TextMate model is computed in a Thread and when it is available the colorization is done.

It works great (with a big file like https://raw.githubusercontent.com/Microsoft/TypeScript/master/lib/tsserver.js) the editor doens't freeze and colorization is done step by step (you can see colorization for the first lines as soon as editor is opened and the other lines are colorized when model si parsed).

But when you try to update th eeditor when colorization is done for big files, TextMate model and editor is not synch.

**Comment by mickaelistria** [comment]
@angelozerr Do you know a deterministic way to reproduce this, using the samples provided in the repo?

**Comment by angelozerr** [comment]
> Do you know a deterministic way to reproduce this, using the samples provided in the repo?

At first this problem comes I when you do copy/paste of big content, or when validation, code folding invalidate text presentation (with my TypeScript Editor). 


If you see `colorize` method https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/text/TMPresentationReconciler.java#L346

It can be called with 2 means:

 * when TM model changed (TextMate is computed). This case is done when IDocument is loaded (when editor is opened) an updated (when user change the editor content).

 * when text presentation  invalidated by annotations like validation (see `textChanged ` https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/text/TMPresentationReconciler.java#L182)

The main idea is to never freeze the editor. When editor is opened, TextMate starts to be computed. as soon as there are TextMate tokens which are computed, the TMModel throws event and the TMPresentationReconclier execute the colorization https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/text/TMPresentationReconciler.java#L262

When annotations invalidate the editor (when validation is done, mark occurrences, etc) the `textChanged ` https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/text/TMPresentationReconciler.java#L182 is called.

So when `textChanged `  is called before the TextMate tokens are computed ( https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/text/TMPresentationReconciler.java#L262), this issue occurs.

**Comment by sebthom** [comment]
@angelozerr do you still have the issues reported here with the current release? I tried copy and pasting big chunks of code and rendering looks fine to me.
