### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by sebthom** [eclipse/tm4e#505]
@mickaelistria I am missing repo permissions to perform the necessary steps. Could you please do it?

**Comment by mickaelistria** [comment]
I don't have such permissions either. But I've pushed a main branch from the HEAD of master and tried to delete the `master` branch. It looks like GitHub doesn't allow to remove `master` branch if it' the default one. Please open an issue to helpdesk requesting that main becomes the default.

**Comment by sebthom** [comment]
OK, opened one: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2797

**Comment by mickaelistria** [comment]
Done.
