### ISSUE TITLE
Wiki no longer available

### ISSUE THREAD

**Issue by zulus** [eclipse/tm4e#510]
I'm unable to find correct WIKI location. All links redirects to main repository :(

**Comment by sebthom** [comment]
@mickaelistria  There is a Wiki link at https://projects.eclipse.org/projects/technology.tm4e pointing to https://github.com/eclipse/tm4e/wiki

![image](https://user-images.githubusercontent.com/426959/225068820-3d8fd478-9708-42d2-b161-d7fb9816df3d.png)

How can we remove that link?

**Comment by mickaelistria** [comment]
OK, I replaced this link with https://github.com/eclipse/tm4e/tree/main/documentation

**Comment by sebthom** [comment]
On the [overview tab](https://projects.eclipse.org/projects/technology.tm4e) it still points to the old URL. The other tabs are fine.

**Comment by sebthom** [comment]
I just realized I have edit permissions too now..
