### ISSUE TITLE
 Cannot figure out how to enable syntax highlighting for my custom text markup

### ISSUE THREAD

**Issue by stanislaw** [eclipse/tm4e#514]
Hello everyone,

I apologize in advance if I missed an important step following this tutorial: [Eclipse TM4E - Sharing features between code editors...](https://www.eclipse.org/community/eclipse_newsletter/2018/june/tm4e.php)

My problem: I followed the tutorial (the `shellscript.tmbundle` example) but I could not get my example Bash code to be syntax-highlighted. I also could not produce a working solution for [my own markup](https://github.com/strictdoc-project/strictdoc.tmLanguage), which is known to work correctly in VS Code and JetBrains PyCharm and WebStorm.

My system:

- My OS: `macOS Monterey 12.6.3`
- My Eclipse version: `Eclipse IDE for C/C++ Developers (includes Incubating components). Version: 2023-03 (4.27.0). Build id: 20230309-1520`

Please let me know what could I do to solve the problem or if I could report further information. Please note that I am not an Eclipse user, but I am happy to dig deeper to understand how to make my markup language work in Eclipse.

Below, I provide the screenshots of how I was following the tutorial's steps:

----

First, I do have the .sh and my .sdoc extensions registered:

<img width="1302" alt="Bildschirmfoto 2023-03-25 um 23 20 00" src="https://user-images.githubusercontent.com/452547/227745244-651fd444-7956-4e3b-afae-4e3f15727797.png">

----

Next, I did integrate the `shellscript.tmbundle` file:

<img width="1302" alt="Bildschirmfoto 2023-03-25 um 23 20 34" src="https://user-images.githubusercontent.com/452547/227745400-e21b5864-04d5-4298-8083-2a235493fe41.png">

----

I also integrated my markup file similarly. Note that the Preview recognizes my markup.

<img width="1302" alt="Bildschirmfoto 2023-03-25 um 23 21 30" src="https://user-images.githubusercontent.com/452547/227745464-859ea267-d81f-4b4f-aea7-e5c621b2bfab.png">

----

According to the tutorial, I should already see my syntax to be highlighted, however I can see neither the .sh nor the .sdoc files to have their syntax highlighted.

<img width="1346" alt="Bildschirmfoto 2023-03-25 um 23 21 09" src="https://user-images.githubusercontent.com/452547/227745507-26ea7b33-d923-4bb5-9c97-5b70eac28c64.png">
<img width="1346" alt="Bildschirmfoto 2023-03-25 um 23 34 42" src="https://user-images.githubusercontent.com/452547/227745522-4b0adf9a-e005-4382-be6a-2f9b9ca04628.png">

----

One observation: The built-in Jinja files do have their `Content type bindings` populated, but my Shell and SDoc grammars do not.

<img width="554" alt="Bildschirmfoto 2023-03-25 um 23 35 36" src="https://user-images.githubusercontent.com/452547/227745567-e68c376b-d071-4110-984a-da41de1643c9.png">
<img width="551" alt="Bildschirmfoto 2023-03-25 um 23 35 43" src="https://user-images.githubusercontent.com/452547/227745568-3911c332-a677-4d91-9e97-c65cda2f7fcf.png">

<img width="555" alt="Bildschirmfoto 2023-03-25 um 23 35 30" src="https://user-images.githubusercontent.com/452547/227745565-3f7df5df-4faa-498b-ad49-f6035acd8e98.png">

**Comment by mickaelistria** [comment]
(Note that for .sh file, you may want to try ShellWax, which does provide syntax highlighting and more.)
Have you tried to open the file with the "Generic Text Editor"?

**Comment by stanislaw** [comment]
> (Note that for .sh file, you may want to try ShellWax, which does provide syntax highlighting and more.)

Thanks for the tip! I only used the `.sh` because the tutorial uses it as an example. My main focus was to get my markup to be displayed.

>  Have you tried to open the file with the "Generic Text Editor"?

In fact, I didn't, and I didn't know that there are two different editors. I have tried it and it works! Now I am very curious to know why my markup works in the `Generic Text Editor` and doesn't work in the default one?

P.S. I have already documented the steps in my tutorial: https://github.com/strictdoc-project/strictdoc.tmLanguage#installing-in-eclipse.

**Comment by mickaelistria** [comment]
> why my markup works in the Generic Text Editor and doesn't work in the default one?

The default Text Editor is a plain text editor; the Generic Text Editor is an extensible editor which allows customization via extensions; TM4E contributes to the Generic Text Editor such an extension to provide highlighting; but doesn't participate in the plain Text Editor.
I think we should consider making the Generic Text Editor the default in Eclipse Platform, as it does usually provide better results. Can you please open an issue against eclipse-platform org/repo to suggest that ?

**Comment by mickaelistria** [comment]
I'm closing issue here; the topic of editor association is not something that is owned by TM4E, but by Platform.
