### ISSUE TITLE
Fix issues spot by SonarQube/Findbugs

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#54]
Static analysis show multiple errors in the code that for sure will lead to bugs or under-efficient code. They are reported at https://dev.eclipse.org/sonar/dashboard/index/149544 . At least, the Blocker and Critical issues should be fixed.

**Comment by angelozerr** [comment]
> At least, the Blocker and Critical issues should be fixed.

Yes sure. Any PR are welcome!

**Comment by mickaelistria** [comment]
The board indeed doesn't exist any more. Using SonarLint in any good IDE does the work well. Let's close this issue.
