### ISSUE TITLE
Language Configuration preference page layout is incorrect.

### ISSUE THREAD

**Issue by raghucssit** [eclipse/tm4e#552]
Language configuration table/composite should grab the excess vertical space.
![tm-pp-wrong](https://github.com/eclipse/tm4e/assets/10301131/13ea63b6-4213-456e-a47b-ad2bb634acb0)

**Comment by sebthom** [comment]
Nice find. A PR is welcome!

**Comment by sebthom** [comment]
Just merged your PR. Thanks!
