### ISSUE TITLE
Theme that replicates the coloring of the WTP XML editor

### ISSUE THREAD

**Issue by kevloral** [eclipse/tm4e#572]
Having a theme that replicated the coloring scheme used in the WTP XML editor would be nice.

**Comment by angelozerr** [comment]
Any contribution are welcome!

**Comment by kevloral** [comment]
The theme is called "Traditional" and it is quite close to the syntax coloring scheme used in the WTP XML editor. It is not perfect, though, as some elements that would colored differently in the original editor share the same CSS here. For the time being, the only difference I have been able to find can be seen on this screenshot, but there could be more:

![image](https://github.com/eclipse/tm4e/assets/3647248/25040129-576d-4b2f-b093-df66aa5a825e)

In the original WTP editor, the equals sign would be black, but here that sign shares the same CSS (.meta.tag) as the tag delimiters.

**Comment by sebthom** [comment]
If the theme is specific for XML files, maybe it should be added to the language pack instead of the default UI plugin and be named "WTP XML Classic" or something like this?

**Comment by kevloral** [comment]
You are both right. I named it _Traditional_ because, as you may imagine, I have started using this XML editor after having used the WTP XML editor for years. Therefore, I agree something along the lines of "WTP XML Classic" would be much more appropriate.

**Comment by angelozerr** [comment]
> If the theme is specific for XML files,

It is specific for WTP, in other words CSS, XML, HTML.

> Therefore, I agree something along the lines of "WTP XML Classic" would be much more appropriate.

+1

> maybe it should be added to the language pack

I have not strong opinion about that

**Comment by sebthom** [comment]
We could also just call the theme `WTP` if it was used by WTP for more than just XML files.

**Comment by kevloral** [comment]
Please note that I have only tested the new theme with XML files.

**Comment by sebthom** [comment]
@kevloral you seemed to have closed your PR. Is this enhancement not needed anymore?

**Comment by kevloral** [comment]
My bad. I thought it had already been merged. I have a local copy of the .css file, so I will use it to create a new PR for this.
