### ISSUE TITLE
Can't add a Language Configuration

### ISSUE THREAD

**Issue by NicoPy** [eclipse/tm4e#582]
Hi, 

I'm trying to add a new Language configuration. 
I can select the language file but the _"Content Type"_ area is empty. Nothing to select. Typing some entry always says "Invalid content type id inputted".

![image](https://github.com/eclipse/tm4e/assets/8762261/89f03bdd-c918-4acb-a79f-723be24b07fe)

Any workaround ?

Note : I'm using last Eclipse and TextMate versions (updated today) on Windows 10.

**Comment by sebthom** [comment]
I never used that page but this is a bug. A workaround is probably that you manually enter the content type ID into the text field.

**Comment by sebthom** [comment]
Thanks for reporting the issue. You can try the latest snapshot build at https://download.eclipse.org/tm4e/snapshots/ which incorporates the fix.

**Comment by NicoPy** [comment]
Thanks for the quick fix.
