### ISSUE TITLE
Error occurs while opening a java/txt file using generic text editor

### ISSUE THREAD

**Issue by Dinesh0723** [eclipse/tm4e#585]
Pre-conditions:
Eclipse Version: 2023-06 (4.28.0)
Build id: 20230608-1333
OS - Windows10
Streps to reproduce:

Open "Open resource" window
Type "*.java" or "*.txt" and select the file.
Right click on the selected file and select open with-> Generic text editor->Unable to open the file (error - Failed to create the parts controls)

**Comment by angelozerr** [comment]
See in your log perhapd it is the same issue than https://github.com/eclipse/tm4e/issues/578

**Comment by sebthom** [comment]
Try to install the latest release of tm4e from [download.eclipse.org/tm4e/releases/0.8.0](https://download.eclipse.org/tm4e/releases/0.8.0/)

**Comment by sebthom** [comment]
Closing issue for now. Feel free to reopen if problem persists.
