### ISSUE TITLE
Consider migrating away from guava library (or make its use internal)

### ISSUE THREAD

**Issue by laeubi** [eclipse/tm4e#607]
Google Guava is a collection of useful things but there also lies its weakness as this results in big size, and heavy dependencies on specific versions even if not all parts are affected. Also with today modern java many things can be archived with plain java as well.

As it is know to create dependency-hell problems, I'd like to suggest to:

1. replace all usages where possible with standard java
2. embeds the code that can't be replaced easily in an internal package

See 
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1476

for a discussion where the usage of guava currently prevents usage of LSP4J in eclipse-platform while it seems a technology that should be used even **more** there and currently requires several plugins to ship their own what can then create even more problems of competing versions.

See also
- https://github.com/eclipse-lsp4j/lsp4j/issues/771
- https://github.com/eclipse/lsp4e/issues/865

**Comment by sebthom** [comment]
Done

**Comment by laeubi** [comment]
@sebthom wow that's great news!

**Comment by vogella** [comment]
@sebthom super impressive. Thanks
