### ISSUE TITLE
Cannot create grammar using 'shell-unix-bash.tmLanguage.json'.

### ISSUE THREAD

**Issue by raghucssit** [eclipse/tm4e#619]
I am trying to create a new grammar by re-using the shell-unix-bash.tmLanguage.json provided in language pack. I have downloaded this file and kept in workspace.
When i use this file for creating grammar i am getting below error. And it did not create any grammar.
![cannot-add-grammar](https://github.com/eclipse/tm4e/assets/10301131/b0689ee6-cdcd-4cfa-83ed-7c10141878be)
grammar file i am using.
[shell-unix-bash.tmLanguage.json](https://github.com/eclipse/tm4e/files/13297758/shell-unix-bash.tmLanguage.json)

**Comment by sebthom** [comment]
The error message is currently misleading (which is fixed in the snapshot version of tm4e already) . probably a parsing error occurred and thus the grammar is not loaded. you should see an error in the eclipse error log file in your workspace.

**Comment by sebthom** [comment]
@raghucssit do you still have this issue using the TM4E snapshot version from https://download.eclipse.org/tm4e/snapshots/

If so please post a corresponding stacktrace. thanks!

**Comment by sebthom** [comment]
TM4E 0.9.0 is released and should fix that issue. Reopen the issue if needed.

**Comment by iloveeclipse** [comment]
Thanks!
