### ISSUE TITLE
RFE: bazel grammar support

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse/tm4e#666]
I wonder if there is a grammar for bazel build language that could be added to tm4e? Would be nice to have.

**Comment by mickaelistria** [comment]
Have you tried using the full bazel-eclipse plugin? It seems to include such a grammar: https://github.com/salesforce/bazel-eclipse/blob/main/bundles/com.salesforce.bazel.eclipse.ui/plugin.xml#L85 (however, https://marketplace.eclipse.org/content/bazel-eclipse-feature says it's been discontinued)

**Comment by sebthom** [comment]
We are currently only sourcing the grammar files from vscode. I am not really interested in adding more sources as this requires manual IP approvals for each update.

But if it helps, I added the bazel syntax here https://github.com/sebthom/extra-syntax-highlighting-eclipse-plugin

**Comment by sebthom** [comment]
Closing the issue for now as a `wontfix`. 

Btw. looking at the commit stats of the [bazel-eclipse](https://github.com/salesforce/bazel-eclipse/graphs/contributors) plugin the development activity has increased again in the last six months so maybe the marketplace info about it being discontinued is outdated.
![image](https://github.com/eclipse/tm4e/assets/426959/22687277-e82d-49e9-a3bc-d369e8c3c9f5)

**Comment by mickaelistria** [comment]
> Btw. looking at the commit stats of the [bazel-eclipse](https://github.com/salesforce/bazel-eclipse/graphs/contributors) plugin the development activity has increased again in the last six months so maybe the marketplace info about it being discontinued is outdated.

Interesting, thanks a lot for sharing this finding!
