### ISSUE TITLE
Improve Thread sync in AbstractTMModel

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#69]
The AbstractTMModel is a complex class, with a lot of `synchronized`. We should find out ways to simplify it and better separate the thread and the model. I suggest we try to make the `BackgroundThread` static and we avoid to consume fields from AbstractTMModel directly, and try to avoid sharing any reference and pass arguments by value as much as possible. That should progressively remove all needs for `synchronized` and should hopefully improve performance.

**Comment by angelozerr** [comment]
> The AbstractTMModel is a complex class, with a lot of synchronized. 

So ugly class!!! If I remember I have tried to use some pieces of code from `org.eclipse.jface.text.reconciler.AbstractReconciler`  but class is became so uggly -(

> That should progressively remove all needs for synchronized and should hopefully improve performance.

I trust you Mickael!

**Comment by mickaelistria** [comment]
Another issue is that at the moment the `fDirtyRegionsQueue` or `lines` don't track whether there's still job to perform. Instead of checking the `lines`, the thread should check such a queue of regions to process.
This is probably better being tracked in a separate commit.

**Comment by mickaelistria** [comment]
I have the impresion that the _invalidLineStartIndex is enough to check whether to wait or not.

**Comment by mickaelistria** [comment]
I think the invalid lines should be managed by a PriorityBlockingQueue. The model would populate it, and the thread would consume the it. This structure is pretty simple to use and probably the most efficient available to manage a list of lines to process.

**Comment by angelozerr** [comment]
@mickaelistria I trust you, I have none idea about your suggestion.

**Comment by angelozerr** [comment]
@mickaelistria I think we can close this issue, no?

**Comment by mickaelistria** [comment]
Yes, There might be other possible changes, but the current state is somehow what I expected by opening this issue and I do not have an idea of another worthy improvement there.
