### ISSUE TITLE
IncludeReference SELF definition is incorrect

### ISSUE THREAD

**Issue by janyou** [eclipse/tm4e#723]
https://github.com/eclipse/tm4e/blob/33dbe0128a1f061b422cc49ca61a5f1f94e4cf8e/org.eclipse.tm4e.core/src/main/java/org/eclipse/tm4e/core/internal/grammar/dependencies/IncludeReference.java#L37

**Correct：**
`private static final IncludeReference SELF = new IncludeReference(Kind.Self, RawRepository.DOLLAR_SELF, "");
`

**Comment by sebthom** [comment]
Good catch, thanks a lot!!
