### ISSUE TITLE
Allow to "wrap" a selected word when typing an opening bracket

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tm4e#727]
From selected `selectedWord` in an editor (with LSP4E language config and bracket insertion enabled)
I type `(` (or any single char what is matching one of the declared opening brackets)
EXPECTED: `(selectedWord)`, wrapped with the brackets
GOT: `(` word lost

The expected behavior is often more convenient and is used by some other code editors. The "legacy" behavior would only require user to type "DEL" before inserting there bracket, which isn't too much of a pain and seems minor compared to the comfort of the proposed behavior.

This echoes https://github.com/eclipse-platform/eclipse.platform.ui/issues/865

**Comment by sebthom** [comment]
Please try the latest snapshot.
