### ISSUE TITLE
Registering local grammar injection in plugin.xml no longer works.

### ISSUE THREAD

**Issue by andrewL-avlq** [eclipse/tm4e#733]
Injection bindings in plugin.xml of the form

      <injection
            scopeName="source.foo"
            injectTo="source.bar">
      </injection>

no longer seem to work, but require the plugin id to be present, like

      <injection
            scopeName="source.foo"
            injectTo="source.bar@plugin.id">
      </injection>

even when both grammars are defined in the current plugin.
Is this an intentional feature change? Or a regression?

**Comment by sebthom** [comment]
this is a regression, plugin developers should not have to deal with the internal scope names. please try the latest snapshot from https://download.eclipse.org/tm4e/snapshots/

**Comment by andrewL-avlq** [comment]
That fixes it, thanks.

Any idea on what timescale the fix will be available in a release?

**Comment by sebthom** [comment]
I just released 0.11.0
