### ISSUE TITLE
Build hangs on executing test class : org.eclipse.tm4e.core.grammar.test.VSCodeTextMateTest

### ISSUE THREAD

**Issue by ainslec** [eclipse/tm4e#76]
When building via maven, the "org.eclipse.tm4e.core.grammar.test.VSCodeTextMateTest" does not complete.

Hangs on test "org.eclipse.tm4e.core.grammar.test.VSCodeTextMateTest":
----
mvn clean verify 
----

Does not hang (workaround):

----
mvn clean verify -Dskiptests
----

**Comment by angelozerr** [comment]
Have you again the problem?

**Comment by ainsley** [comment]
Starting this at 21:58 BST. I'll report when or if it completes.

**Comment by ainsley** [comment]
Started running the VSCodeTextMateTest at 21:59

**Comment by ainsley** [comment]
22:09 -- still going, 1 core maxed out at 100%

**Comment by ainsley** [comment]
23:34 still not finished

![fgsfds6](https://cloud.githubusercontent.com/assets/201870/24479663/42de28a4-14d8-11e7-9a7c-bdd798c94d92.png)

I'm killing the build now, after 85 minutes.

**Comment by angelozerr** [comment]
Our build seems working.

@ainsley it's hard to know if it's a conf problem from you.

@ainsley @mickaelistria whar do you think about this issue? Can we close it?

**Comment by angelozerr** [comment]
@ainslec can we close this issue?

**Comment by angelozerr** [comment]
None answer, I close this issue. Please reopen it if you have troubles again.
