### ISSUE TITLE
Paste into editor (JS) adding extra tabs

### ISSUE THREAD

**Issue by jridge-ezclocker** [eclipse/tm4e#788]
NOTE: This could be related to a similar issue reported at: https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/issues/1525

Searched around but didn't find an issue that seemed to match so forgive me if it is fixed in a future release or already reported :)

### Main Issue: Paste Adds Unnecessary Tabs
When pasting code from another file into the editor additional unnecessary tabs get added. Example below:

1) Starting with a basic JS class:
![initial](https://github.com/user-attachments/assets/0bc811f1-fc85-4c64-b9f6-dd4bb0dde494)

2) Copy a property with getter/setter from another class (could also just be a method or code within a method):
![copy-from-different-file](https://github.com/user-attachments/assets/693929e7-2028-43d0-b095-2a10f45f9a05)

3) Paste the copied code into the initial file:
![past-into-initial-file](https://github.com/user-attachments/assets/ed9aea16-8f5f-4813-86fe-76e9bf7e4a32)

Notice the tabbing that is applied during the paste.

4) From the cursor position after the initial paste, paste the code again
![paste-again-into-initial-file](https://github.com/user-attachments/assets/e7c42580-78c5-4a62-8508-3b02e00a102c)

Notice the additional tabbing that is applied during the paste.

5) Formatting the code in the initial file does fixe most of the tab issues, however, the comments never get formatted properly:
![format-after-paste](https://github.com/user-attachments/assets/70e43609-6efa-41bc-8f26-e510d34d738a)

### Secondary Issue
Finally, an (I'm assuming) related issue involves adding a new line to a method (example), and backspacing to the beginning of the line, at that point the tab key does nothing at all:

1) Add a New Line to the Method
![add-new-line](https://github.com/user-attachments/assets/00d13ea7-7fe8-4b2d-86e6-0d3468472843)

2) Backspace (twice in this case) to the beginning of the line
![back-space-back-space-cannot-tab](https://github.com/user-attachments/assets/04366ab4-bec9-455e-8ccc-2c167a763542)

3) Pressing the tab key does nothing in the editor (cursor remains on the first column of line)

To get the tab key to function again I have to type at least one character and then go back to the beginning of the line to use the tab. Formatting normally fixes the issues as well unless a template literal multi-line string was entered (since formatting will ignore the template literal string formatting).

Just let me know if you would like the last item reported separately.

### Eclipse Environment

- Version: 2024-06 (4.32.0)
- Build id: 20240606-1231
 
#### Select Plugin/Feature Versions
- **TM4E Related**
-- Language Configurations (com.genuitec.eclipse.tm4e.languageconfiguration): v2024.3.1.202407230323	
-- Language Configurations (org.eclipse.tm4e.languageconfiguration): v0.12.1.202407191108
-- Language Pack (org.eclipse.tm4e.language_pack): v0.12.0.202405210827
-- Registry management (org.eclipse.tm4e.registry): v0.12.1.202406131414
-- UI (org.eclipse.tm4e.ui): v0.12.1.202407191108
-- TextMate support in Java (org.eclipse.tm4e.core): v0.12.1.202407191108
- **LS4J Related**
-- LSP4J (org.eclipse.lsp4j): v0.23.1.v20240521-1815
-- LSP4J Debug (org.eclipse.lsp4j.debug): v0.23.1.v20240521-1815
-- LSP4J JsonRPC (org.eclipse.lsp4j.jsonrpc): v0.23.1.v20240521-1815
-- LSP4J JsonPRC Debug (org.eclipse.lsp4j.jsonrpc.debug): v0.23.1.v20240521-1815	
- **Wild Web Developer**
-- Wild Web Developer HTML, CSS, JSON, Yaml, JavaScript, TypeScript, Node tools: v1.3.6.202405280856
-- Wild Web Developer XML tools: v1.3.4.202405270639

#### More Eclipse Environment Detail
- All Eclipse Software Installed: 
[installed-software.csv](https://github.com/user-attachments/files/16681899/installed-software.csv)
- Select Installed Plugins Information:
[select-plugins.csv](https://github.com/user-attachments/files/16682024/select-plugins.csv)

**Comment by sebthom** [comment]
This might be triggered by an indentation rule. Please try to disable them for the JS content type:

![image](https://github.com/user-attachments/assets/f06a09af-493f-4080-a95f-e8a4d74b0a2b)

**Comment by jridge-ezclocker** [comment]
Thanks for the time - Can confirm that unchecking that box doesn't result in extra tabs during paste. I'll close the defect.
