### ISSUE TITLE
Adding CSS theme in TextMate->Theme preferences page is not working.

### ISSUE THREAD

**Issue by auriusbendikas** [eclipse/tm4e#797]
Steps to reproduce:

1. Download [Monokai.css](/eclipse/tm4e/blob/main/org.eclipse.tm4e.ui/themes/Monokai.css)
2. Open Eclipse preferences (Window->Preferences)
3. Navigate to TextMate->Theme
4. Click "Add" and select downloaded `Monokai.css` file
5. Click "Open" and error message will be displayed.
![image](https://github.com/user-attachments/assets/b117d0cd-6860-4538-a0ef-c308ab95408f)

**Comment by sebthom** [comment]
Is there a stacktrace in the error log?

**Comment by auriusbendikas** [comment]
No,

I could not find any errors or any usefull info in eclipse logs.

**Comment by sebthom** [comment]
Thanks for reporting!
