### ISSUE TITLE
Disturbing output at runtime

### ISSUE THREAD

**Issue by akurtakov** [eclipse/tm4e#86]
At runtime tm4e generates a lot of output like:
Render from: 58 to: 58
Render from: 58 to: 58
Render from: 0 to: 81
Render from: 82 to: 146
Render from: 17 to: 141
Render from: 17 to: 141
Render from: 26 to: 26

This is really disturbing when one tries to debug project that uses tm4e.

**Comment by angelozerr** [comment]
Indeed, I will try to fix that ASAP.

**Comment by angelozerr** [comment]
Issue https://github.com/eclipse/tm4e/issues/88 should fix this issue too. If it's OK @akurtakov please close it.

**Comment by angelozerr** [comment]
@akurtakov could you tell me if we can close this issue please?

**Comment by akurtakov** [comment]
Yes, thanks and sorry for being late with feedback.
