### ISSUE TITLE
Please fill project info

### ISSUE THREAD

**Issue by akurtakov** [eclipse/tm4e#87]
Please fill https://projects.eclipse.org/projects/technology.tm4e with relevant data to make it easier to find data - git repo, p2 sites for installation, releases and etc.

**Comment by angelozerr** [comment]
Yes sure @akurtakov 

I will do that ASAP.

**Comment by angelozerr** [comment]
@akurtakov I have added some info. If it's OK, please close this issue.

**Comment by mickaelistria** [comment]
Seems good to me, closing.
@akurtakov feel free to reopen.
