### ISSUE TITLE
TMPresentationReconciler doesn't work with IStorage

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#89]
`TMPresentationReconciler`  try to discover `IContentType `from a given `IDocument`. It works well when the document is stored in `ITextFileBufferManager `but it doesn't work when document comes from an `IStorage `

(ex : if you open a file from `Team / Show In History` the ITextFileBuffer is null)

**Comment by angelozerr** [comment]
@mickaelistria I have fixed this issue but it's a big hack because I don't know how to retrieve IEditorInput from IDocument with a clean mean. See https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/internal/model/ContentTypeHelper.java#L184

If you find a better solution, don't hesitate to change it. Thanks!

**Comment by angelozerr** [comment]
@mickaelistria please tell me if you are OK with my (ugly) code. Thanks!

**Comment by mickaelistria** [comment]
I hope we'll find some possible cleaner ways of implementing that some day, but at the moment, it does the job well.
