### ISSUE TITLE
Grammar injections to support advanced coloration like Angular @Component/template

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#90]
@mickaelistria I'm implementing grammar injection outside a given grammar.

For instance in my case I have 2 TypeScript grammars (one for ts and one for tsx (TypeScript with JSX) defined liked this.

Here the result:

```xml
   <extension
         point="org.eclipse.tm4e.registry.grammars">
      <grammar
      		scopeName="source.ts"
            path="./syntaxes/TypeScript.tmLanguage.json" >
      </grammar>
      <grammar
      		scopeName="source.tsx"
            path="./syntaxes/TypeScriptReact.tmLanguage.json" >
      </grammar>
</extension>
```
![image](https://cloud.githubusercontent.com/assets/1932211/25373344/9765361c-2999-11e7-963a-9e128b954523.png)

Now I would like to inject in thoses existing grammars Angular2 syntax coloration for @Component/template to colorize styles as CSS and template as HTML to have that:

![image](https://cloud.githubusercontent.com/assets/1932211/25373507/3b54058c-299a-11e7-9dc9-0258a79aed4f.png)

My idea is to improve the `org.eclipse.tm4e.registry.grammars` extension point to write that:

```xml
<extension
   	      point="org.eclipse.tm4e.registry.grammars">
  	      <injections>
   	        <to scopeName="source.ts" />
   	        <to scopeName="source.tsx" />
   	        <grammar path="./syntaxes/templates.ng.json" />
   	        <grammar path="./syntaxes/styles.ng.json" />
   	      </injections>
</extension>
```
This extension point is able to update the existing grammar by adding new TextMate rules to support Angular2.

I have used `to` element and not `tos` element (with scope name separated with ',' for instance) to benefit with scopeName completion. (Same thing for grammar).

What do you think @mickaelistria ? Do you like this feature? Do you like the write of this injections?

Many thanks for your feedback.

**Comment by mickaelistria** [comment]
Shouldn't it be covered by the textmate grammar itself? I thought tm grammars could reference one another; if so, why would we need to redefine a reference mechanism?

**Comment by mickaelistria** [comment]
I forgot to comment in my previous message that I really like the result by the way ;) I'm only curious about the implementation.

**Comment by angelozerr** [comment]
VSCode supports this feature. See https://stackoverflow.com/questions/43125093/can-i-extend-vs-code-textmate-language-grammars and  https://github.com/Microsoft/vscode/commit/a0bda2e0cb0797bbcb7382917641ba31666a0eff 

External grammar injection is a better name (instead of outside grammar)

If we follow the idea of VSCode we could write:

```
<extension
   	      point="org.eclipse.tm4e.registry.grammars">
  	       <grammar scopeName="template.ng"
                                 path="./syntaxes/templates.ng..json" >
                                <injectTo scopeName="source.ts" >
                                <injectTo scopeName="source.tsx" >
               </grammar>
  	       <grammar scopeName="styles.ng"
                                 path="./syntaxes/styles.ng..json" >
                                <injectTo scopeName="source.ts" >
                                <injectTo scopeName="source.tsx" >
               </grammar>
</extension>
```

I think it's better write, no?

>  I'm only curious about the implementation.

It will not very complex. Today internal injections is already implemented https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.registry/src/main/java/org/eclipse/tm4e/registry/internal/GrammarRegistryManager.java#L137

We should just improve that to inject too external grammar which will be defined in the GrammarDefinition https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.registry/src/main/java/org/eclipse/tm4e/registry/internal/GrammarRegistryManager.java#L142

**Comment by mickaelistria** [comment]
Can't the same thing be achieved by putting "injection" directly inside the grammars? ie in that case, can't the source.ts grammar contain directly the reference to the template.ng one?

**Comment by angelozerr** [comment]
> Can't the same thing be achieved by putting "injection" directly inside the grammars?

Yes it's the same thing.

> case, can't the source.ts grammar contain directly the reference to the template.ng one?

You can compare "external injection" with "Eclipse Plugin" which provides news features. For instance me I have:

 * typescript.java plugin which provides ts completion and ts syntax coloration
 * angular2-eclipse which provides angular complation inside ts and I would like now provide angular ts syntax coloration
 * X plugin which could provide X ts syntax coloration.

If I declare template.ng injection inside source.ts, it will work but none other plugins could provide new syntax color. VSCode does that, so I think it's a good idea to do that and it's not very complex to do.

Hope you will understand my explanation.

**Comment by mickaelistria** [comment]
Ok, I think I understand better: referencing from inside grammars put dependencies from host to sub-grammar, whereas injection allows to put the dependency in the other way round.
Sounds like a good feature to add indeed.
About the extension point, I'd rather see a different child of grammars extension. That should allow grammars to be defined in their own plugin (one specific for each language), but reused for injection in another plugin doing some "integration" between both languages:

```xml
<extension point="org.eclipse.tm4e.registry.grammars">
  <grammar scopeName="template.ng" path="./syntaxes/templates.ng..json" />
  <grammar scopeName="styles.ng" path="./syntaxes/templates.ng.json" />
  <injection scope="template.ng" injectTo="source.ts"/>
  <injection scope="template.ng" injectTo="source.tsx"/>
  <injection scope="styles.ng" injectTo="source.ts"/>
  <injection scope="styles.ng" injectTo="source.tsx"/>
</extension>
```

So for example, if some day, *.ng grammars can be used in a coffeescript file, we'd only have to redefine the `injection`s, not the grammar definition. WDYT?

**Comment by angelozerr** [comment]
>  WDYT?

Great idea! I would like just to use` injection /@scopeName` like other extension point:

```xml
<extension point="org.eclipse.tm4e.registry.grammars">
  <grammar scopeName="template.ng" path="./syntaxes/templates.ng..json" />
  <grammar scopeName="styles.ng" path="./syntaxes/templates.ng.json" />
  <injection scopeName="template.ng" injectTo="source.ts"/>
  <injection scopeName="template.ng" injectTo="source.tsx"/>
  <injection scopeName="styles.ng" injectTo="source.ts"/>
  <injection scopeName="styles.ng" injectTo="source.tsx"/>
</extension>
```

**Comment by angelozerr** [comment]
@mickaelistria I hav eimplemented this issue. See wiki at https://github.com/eclipse/tm4e/wiki/UI#external-grammar-injection for more information
