### ISSUE TITLE
Add preview for the themes preference page

### ISSUE THREAD

**Issue by akurtakov** [eclipse/tm4e#91]
It would be really nice to be able to preview the different themes.

**Comment by angelozerr** [comment]
I'm working on this issue https://github.com/eclipse/tm4e/issues/32

For the moment you can view the list of the theme:

![](https://cloud.githubusercontent.com/assets/1932211/25401101/0c8ba1aa-29f5-11e7-8323-c7f776399c5f.png)

**Comment by angelozerr** [comment]
@akurtakov here a little demo with theme preview

![textmatethemepreferencedemo](https://cloud.githubusercontent.com/assets/1932211/25535703/560856e4-2c38-11e7-9061-103592f6f0cd.gif)
:

**Comment by akurtakov** [comment]
Really nice. I can't figure directly what the Preview with: combo is for though. But now I can see myself working further on tweaking to get unintrusive change (aka no colors change in current editor) while replacing it.

**Comment by angelozerr** [comment]
> I can't figure directly what the Preview with: combo is for though.

It's the grammar. You need a grammar to have a preview. What do you suggest?

> But now I can see myself working further on tweaking to get unintrusive change (aka no colors change in current editor) while replacing it.

Sorry I hav enot understood? Have you some problem?

**Comment by akurtakov** [comment]
> It's the grammar. You need a grammar to have a preview. If it's not understandable, what do you suggest?

Preview with grammar:  or even just Grammar:  
Would be more helpful for people like me that jump between too many things too often.

> Sorry I have not understood? Have you some problem?
No, what I mean is that tm4e is getting more and more helpful for my occasional work. Keep up the good work.

**Comment by angelozerr** [comment]
> Preview with grammar: or even just Grammar:

I have updated with `Preview with grammar`

> No, what I mean is that tm4e is getting more and more helpful for my occasional work.

Glad tm4e can help you!

>  Keep up the good work.

Thanks!

**Comment by mickaelistria** [comment]
Great addition @angelozerr , thanks!

**Comment by angelozerr** [comment]
Thanks @mickaelistria ! Glad it please you:)
