### ISSUE TITLE
Big memory consumption 

### ISSUE THREAD

**Issue by mniewrzal** [eclipse/tm4e#92]
I'm playing with tm4e PHP editor and I noticed that opening PHP file can consume enormous amounts of memory. A single file can bump heap size from 200MB to 1100MB. Used memory can be cleaned up by GC but maybe there is a way to optimize this somehow. Tested file isn't small (1,7k) but its also nothing very unusual.  

I had only a moment to check source code and after profiling it looks that lots of memory are used by OnigRegExp and compiling regular expressions.

File for testing:
https://raw.githubusercontent.com/composer/composer/master/src/Composer/Installer.php

**Comment by angelozerr** [comment]
@mniewrzal any contribution are welcome!

**Comment by mniewrzal** [comment]
At the moment it would be nice have confirmation that its known problem and its not only me :)

From what I noticed that those regular expressions are compiled for each opened file. It's by design or it can/should be cached somehow?

**Comment by angelozerr** [comment]
VSCode does that too, that's why I have not cached it.

**Comment by angelozerr** [comment]
> For now I wanted to let you know about this :)

Bad news -( I'm not a big expert so I hope people like you could find solution. 

@mickaelistria if you have time to investigate this issue it should be very cool!

**Comment by mniewrzal** [comment]
I played a little bit more with this case. I created a primitive cache for `org.joni.Regex` in OnigRegExp. Memory usage was decreased but I noticed different side effect of this change. Previously when a larger file was opened I was able to notice how its colored (line after line, from beginning to bottom). It took 1-2 seconds but it was visible. With regular expression cache file is colored immediately. 

I will try to create a patch for this so you can play with it. Just I'm not sure if it will be optimal because my knowledge about tm4e source code it limited.

**Comment by mickaelistria** [comment]
I think caching is a great idea. Saving useless instantiations and reusing objects is definitely the best way to save memory and improve performance. I'll have a look at @mniewrzal 's patch, but I don't see any reason why caching would be bad.

**Comment by mniewrzal** [comment]
With basic cache, tm4e will need to store all compiled regexp for all grammars. It can take memory and it will be constant value for IDE during runtime. This is the only place where something can go bad :)

Next week I will have time to work with this and I will give you more details.

**Comment by mickaelistria** [comment]
Maybe we can consider some lazy or cleaning cache, which only compiles and
cache the regexp when necessary and that "free"s them if they were not
accessed within some time or some operations.

**Comment by mniewrzal** [comment]
> Maybe we can consider some lazy or cleaning cache, which only compiles and
> cache the regexp when necessary and that "free"s them if they were not
> accessed within some time or some operations.

Sure, we have several options but maybe it won't be necessary. I just didn't have time to check how much memory for such basic cache (for several grammars) will be used.

**Comment by angelozerr** [comment]
@mniewrzal which tools are you using to profile memory. JProfiler, https://www.eclipse.org/mat/ ?

Thanks for your suggestion

**Comment by mniewrzal** [comment]
I'm using Yourkit Profiler. I have a commercial license for it. But for open source projects  
you should be able to get a free license: https://www.yourkit.com/purchase/#os_license

I think JProfiler should do the job but I don't have experience with it.

**Comment by angelozerr** [comment]
Thanks @mniewrzal for your suggestion.

After reading again the code, I have seen a big bug with cache that I have fixed in https://github.com/eclipse/tm4e/commit/81fcb8daf32f6b832cf873dbba7412215d9b0227 

As I have done a lot of copy/paste from vscode-textmate which is written in TypeScript, my Java translation  was not good. The `||` syntax doesn't do the same thinh between TypeScript (JavaScript) and Java.

Good catch @mniewrzal !

Please tell me if it fixes this issue.

**Comment by mniewrzal** [comment]
Yes! After your fix coloring is done faster and consume much less memory :)

Good work!
