### ISSUE TITLE
[Preferences] Snippet extension point for grammar preview

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#93]
When you select a grammar, the preview text field is not filled. You can see that in this demo:

![](https://cloud.githubusercontent.com/assets/1932211/25525302/7754a4da-2c0e-11e7-851d-8995d435d683.gif)

It should perhaps good to provide a `snippet` extension point to fill the preview text field  with the code. Each grammar could define one or several snippet code to fill the preview.

The extension point could like this:

```xml
<extension
         point="org.eclipse.tm4e.ui.snippets">
      <snippet
           name="A JavaScript sampel 1"
      	    scopeName="source.js"
            path="./snippets/JavaScriptSnippetCode.js" >
      </snippet>
      <snippet
           name="A JavaScript sample 2"
      	    scopeName="source.js"
            path="./snippets/JavaScriptSnippetCode2.js" >
      </snippet>      
</extension>
```

What do you think @mickaelistria about that?

**Comment by mickaelistria** [comment]
This looks great. Yes, a default snippet text would be nice, good idea!

**Comment by jonas-jonas** [comment]
This seems to be implemented?

I used it to register a snippet, but it looks like the theme for the snippet is only loaded after a second click on the grammar. See gif.

Tm4e version: 0.3.3 (from the update site)

![Peek 2019-07-22 14-59](https://user-images.githubusercontent.com/5540255/61634307-55216c80-ac91-11e9-8977-13dec4b5ecc6.gif)

**Comment by mickaelistria** [comment]
This was indeed implemented a while ago, let's close.
