### ISSUE TITLE
[Preferences] TextMate User Preferences (persistent)

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#94]
Today TextMate Grammar and Theme Preferences shows UI Preferences for grammars, themes defined byt extension point. It should b every cool if user could register grammar, themes and stores their preferences.

**Comment by angelozerr** [comment]
@mickaelistria I have done my big refactoring and even if it's not finished, it starts working:

 * you can register a textMate grammar with the "Import textMate grammar" wizard which is available with File/Import or New button from the Grammar preferences page.
 * once you validate the preferences, it stores (with JSON format) the grammar in the eclipse preferences. 
 * to consume your registered grammar, you can open the file with TMEditor which extends TextEditor and return TMPresentationreconciler https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui.editor/src/main/java/org/eclipse/tm4e/ui/editor/internal/TMTextEditor.java

Today grammar/content type binding is not managed (I use fileTypes from the TextMate grammar).

It's not finished, but if you have any questions, suggestions you are welcome!

**Comment by mickaelistria** [comment]
The current registry has enabled to define local grammars & themes for a while.
